import { readInspection, inspectionPath } from '../runtime/inspection.js';
import {directFreeProvider} from '../core/inference-policy.js';
import { providerRegistry } from '../runtime/free-pool/registry.js';
import { PoolUnavailableError } from '../runtime/free-pool/types.js';
import { completionSSE } from '../runtime/free-pool/transport.js';
import { localModelSelectionId } from '../runtime/ollama.js';
import { OpenAPIHono, createRoute, z } from '@hono/zod-openapi';
import { serveStatic } from '@hono/node-server/serve-static';
import { streamSSE } from 'hono/streaming';
import { getCookie, setCookie } from 'hono/cookie';
import { createHash, createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import { readFileSync, existsSync, statfsSync } from 'node:fs';
import { freemem, totalmem, loadavg } from 'node:os';
import { join } from 'node:path';
import { CompanyStore } from '../storage/store.js';
import { DomainError } from '../core/types.js';
import { LocalRuntime } from '../runtime/index.js';
import { Scheduler } from '../scheduler/scheduler.js';
import { CorporateBroker } from '../tools/broker.js';
import { redact } from '../tools/process.js';
import { safeChild } from '../tools/workspaces.js';
import { sourceRoot, writePrivate } from './paths.js';
import { doctor } from './doctor.js';
const jsonSchema=z.any();
const errorSchema=z.object({error:z.object({code:z.string(),message:z.string()})});
const equal=(a:string,b:string)=>{const aa=Buffer.from(a),bb=Buffer.from(b);return aa.length===bb.length&&timingSafeEqual(aa,bb);};
const response={200:{description:'Current validated company result',content:{'application/json':{schema:jsonSchema}}},400:{description:'Invalid command',content:{'application/json':{schema:errorSchema}}},401:{description:'Authentication required',content:{'application/json':{schema:errorSchema}}},403:{description:'Authority denied',content:{'application/json':{schema:errorSchema}}},409:{description:'State conflict',content:{'application/json':{schema:errorSchema}}}};
export function ownerApp(options:{store:CompanyStore;runtime:LocalRuntime;broker:CorporateBroker;scheduler:Scheduler;getUrl:()=>string}){
 const {store,runtime,broker,scheduler}=options;const tokenPath=join(store.dataRoot,'owner-token');if(!existsSync(tokenPath))writePrivate(tokenPath,randomBytes(32).toString('base64url'));const ownerToken=readFileSync(tokenPath,'utf8').trim();const browserSession=createHmac('sha256',ownerToken).update('OpenCorp browser session v1').digest('base64url');const tickets=new Map<string,number>();
 store.events.on('event',(event:any)=>{if(!['runtime.inference.failed','runtime.inference.finished'].includes(event.type))return;const payload=event.payload?.payload??event.payload;const modelId=payload?.modelId??store.get('runs',event.payload?.runId??'')?.modelId;if(typeof modelId!=='string'||modelId==='free-pool')return;const provider=directFreeProvider(modelId)??(modelId.endsWith(':free')?'openrouter':'local');store.update('company',store.company.id,{providerFailures:{...store.company.providerFailures,[provider]:event.type==='runtime.inference.finished'?null:{observedAt:new Date().toISOString(),modelId,status:Number.isInteger(payload?.upstreamStatus)?payload.upstreamStatus:undefined}}});});

 const app=new OpenAPIHono({defaultHook:(result,c)=>{if(!result.success)return c.json({error:{code:'validation',message:result.error.message}},400);}});
 app.onError((error,c)=>{const status=error instanceof DomainError?error.status:500;return c.json({error:{code:error instanceof DomainError?error.code:'internal_error',message:redact(error.message)}},status as any);});
 app.use('*',async(c,next)=>{const url=new URL(options.getUrl());const host=c.req.header('host');if(host!==url.host)return c.json({error:{code:'host_denied',message:'Use the discovered loopback URL.'}},403);const origin=c.req.header('origin');if(origin&&origin!==url.origin)return c.json({error:{code:'origin_denied',message:'Unrelated request origins are not allowed.'}},403);c.header('X-Content-Type-Options','nosniff');c.header('Referrer-Policy','no-referrer');c.header('Cache-Control','no-store');c.header('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");await next();});
 app.get('/health',c=>c.json({application:'OpenCorp',version:'0.1.0',pid:process.pid,state:store.company.state},200));
 app.get('/login',c=>{const ticket=c.req.query('token')??'';const expiry=tickets.get(ticket);tickets.delete(ticket);if(!expiry||expiry<Date.now())return c.html('<!doctype html><html lang="en"><title>OpenCorp sign in</title><body><h1>OpenCorp</h1><p>This sign-in link expired. Run <code>opencorp open</code> to open your company.</p></body></html>',401);setCookie(c,'opencorp_session',browserSession,{httpOnly:true,sameSite:'Strict',secure:false,path:'/',maxAge:30*24*3600});return c.redirect('/');});
 app.use('/api/*',async(c,next)=>{const bearer=c.req.header('authorization')?.replace(/^Bearer /,'')??'';const cookie=getCookie(c,'opencorp_session')??'';if(!equal(bearer,ownerToken)&&!equal(cookie,browserSession))return c.json({error:{code:'unauthorized',message:'Owner authentication required. Run opencorp open.'}},401);await next();});
 app.get('/api/v1/inference/providers',c=>c.json({registry:providerRegistry,configured:runtime.freePool?.status()??[]}));
 app.post('/api/v1/inference/chat/completions',async c=>{
  if(!store.policy.freeInferencePool||!runtime.freePool)throw new DomainError('pool_disabled','Enable the free inference pool in Owner policy',409);
  const text=await c.req.text();if(text.length>2_000_000)throw new DomainError('context_limit','Inference request too large',400);
  const input=z.object({model:z.literal('free-pool').default('free-pool'),messages:z.array(z.any()).min(1),tools:z.array(z.any()).optional(),tool_choice:z.any().optional(),max_tokens:z.number().int().min(1).max(16384).optional(),temperature:z.number().min(0).max(2).optional(),response_format:z.object({type:z.literal('json_object')}).strict().optional(),quality:z.union([z.literal(1),z.literal(2),z.literal(3)]).optional(),purpose:z.enum(['work','evaluation']).default('work'),dataClass:z.enum(['public','internal','confidential']).default('internal'),stream:z.boolean().default(false)}).strict().parse(JSON.parse(text));
  try{const completion=await runtime.freePool.generate(input,c.req.raw.signal);return input.stream?c.body(completionSSE(completion),200,{'content-type':'text/event-stream'}):c.json(completion);}
  catch(error){if(error instanceof PoolUnavailableError){c.header('retry-after',String(Math.max(1,Math.ceil((error.retryAt-Date.now())/1000))));return c.json({error:{code:'free_pool_unavailable',message:error.message}},429);}throw error;}
 });
 app.openapi(createRoute({method:'post',path:'/api/v1/session',responses:response}),c=>{const ticket=randomBytes(24).toString('base64url');for(const [key,expiry] of tickets)if(expiry<Date.now())tickets.delete(key);tickets.set(ticket,Date.now()+60_000);return c.json({url:`${options.getUrl()}/login?token=${encodeURIComponent(ticket)}`},200);});
 app.openapi(createRoute({method:'get',path:'/api/v1/state',responses:response}),c=>{const state=store.snapshot(),disk=statfsSync(store.dataRoot);state.resources={...state.resources,observedAt:new Date().toISOString(),host:{totalMemoryBytes:totalmem(),freeMemoryBytes:freemem(),loadAverage:loadavg(),availableDiskBytes:disk.bavail*disk.bsize},supervisor:{pid:process.pid,uptimeSeconds:process.uptime(),residentBytes:process.memoryUsage().rss},runtime:runtime.status()};return c.json(state,200);});
 for(const collection of ['products','projects','employees','departments','positions','assignments','runs','decisions','attention','models','integrations','messages','artifacts','reviews','actions','logs'] as const)app.openapi(createRoute({method:'get',path:`/api/v1/${collection}`,responses:response}),c=>c.json(collection==='logs'?store.snapshot().events:collection==='messages'?store.snapshot().messages:store.list(collection),200));
 app.get('/api/v1/providers',async c=>{const providers=await runtime.providerStatus();for(const row of providers){const last=store.company.providerTests?.[row.id];if(last){row.lastTest=last;if(last.quotaHeaders)row.quota={status:'unknown',observedAt:last.finishedAt,modelId:last.modelId,headers:last.quotaHeaders};if(row.health!=='red'&&row.configured&&row.modelIds.includes(last.modelId)&&(!row.audit.verifiedAt||Date.parse(row.audit.verifiedAt)<=Date.parse(last.startedAt))){row.health=last.status==='failed'?'red':Date.now()-Date.parse(last.finishedAt)<3600000?'green':'unknown';row.reason=last.status==='failed'?'Last actual test failed':row.health==='green'?'Synthetic response and tool test passed within the last hour':'Last successful test is stale';}}if(row.id==='openrouter'){const backoff=store.providerBackoff();if(backoff){row.cooldown={retryAt:backoff.retryAt,basis:backoff.basis};if(backoff.rateLimitHeaders)row.quota={status:'unknown',observedAt:backoff.observedAt,modelId:backoff.modelId,headers:backoff.rateLimitHeaders};if(Date.parse(backoff.retryAt)>Date.now()){row.health='red';row.reason='Actual HTTP 429; retry cooldown active';}}}const failure=store.company.providerFailures?.[row.id];if(failure&&(!last||Date.parse(failure.observedAt)>Date.parse(last.finishedAt))){row.health='red';row.reason='Actual inference failed after last test'+(failure.status?' (HTTP '+failure.status+')':'');}}return c.json({providers});});
 app.post('/api/v1/providers/test',async c=>{const data=z.object({provider:z.enum(['openrouter','groq','gemini','zai']),modelId:z.string().min(1).max(200)}).strict().parse(await c.req.json());let result;try{result=await runtime.testProvider(data.provider,data.modelId);}catch{throw new DomainError('provider_test_unavailable','Provider busy, unconfigured, or free eligibility unavailable',409);}store.update('company',store.company.id,{providerTests:{...store.company.providerTests,[data.provider]:result}});store.emit('provider.test',{provider:data.provider,status:result.status,modelId:data.modelId});return c.json(result);});
 app.get('/api/v1/workplace',c=>c.json((store.snapshot() as any).workplace));
 app.get('/api/v1/recruitment',c=>c.json(store.list('experiences').filter(r=>['requisition','candidate','skill-source','skill-catalog'].includes(r.kind))));
 app.post('/api/v1/models/micro',async c=>{if(!['paused','stopped'].includes(store.company.state))throw new DomainError('pause_required','Pause before model installation');const raw=await c.req.text();const selection=raw?z.object({modelIds:z.array(z.enum(['micro-06','micro-17','micro-4'])).min(1).max(3)}).strict().parse(JSON.parse(raw)):undefined;const models=await runtime.installMicroModels(selection?.modelIds);for(const model of models)store.put('models',{...model,id:localModelSelectionId(model),name:localModelSelectionId(model)===model.id?model.name:model.sourceAlias});return c.json({models:models.map(m=>({id:m.id,artifactIdentity:m.artifactIdentity,size:m.size}))});});
 const applyControl=async(action:string)=>{store.command({kind:'owner'},{type:'control',action});if(action==='pause'||action==='stop')await scheduler.pause(action==='stop');else scheduler.start();return store.snapshot();};
 app.openapi(createRoute({method:'post',path:'/api/v1/control',request:{body:{required:true,content:{'application/json':{schema:z.object({action:z.enum(['pause','resume','start','stop'])}).strict()}}}},responses:response}),async c=>c.json(await applyControl(c.req.valid('json').action),200));
 app.openapi(createRoute({method:'post',path:'/api/v1/command',request:{body:{required:true,content:{'application/json':{schema:z.object({type:z.string().min(1)}).passthrough()}}}},responses:response}),async c=>{const command=c.req.valid('json');if(command.type==='control')return c.json(await applyControl(String(command.action)),200);const result=store.command({kind:'owner'},command);if(command.type==='policy.update')await scheduler.configureResources();return c.json(result,200);});
 app.openapi(createRoute({method:'post',path:'/api/v1/chat',request:{body:{required:true,content:{'application/json':{schema:z.object({content:z.string().trim().min(1).max(20000),projectId:z.string().optional(),employeeId:z.string().optional()}).strict()}}}},responses:response}),c=>{const data=c.req.valid('json');const employee=data.employeeId?store.need('employees',data.employeeId):store.list('employees').find(e=>e.status==='active'&&store.level(e.id)==='ceo');if(!employee||employee.status!=='active')throw new DomainError('recipient_unavailable','Recipient is unavailable.',409);const message=store.command({kind:'owner'},{type:'message.send',...data,recipientId:employee.id});store.put('assignments',{employeeId:employee.id,supervisorId:employee.homeManagerId??employee.id,projectId:data.projectId??null,title:'Respond to Owner conversation',instructions:`Owner message ${message.id}: ${data.content}\nAnswer this actual message in your final response; the scheduler automatically persists your attributed reply in the Owner conversation. Use relevant evidence and authorized tools when the request needs them. A request for acknowledgment needs only a brief acknowledgment, without product communication or unsolicited portfolio work. Owner conversational text does not itself change reserved spending or access policy; those require explicit Owner controls.`,acceptance:['Answer the actual Owner message; a brief acknowledgment suffices when that is all the Owner requested.'],dependencies:[],status:'queued',priority:80,attempts:0,corrections:0,kind:'conversation',availableAt:new Date().toISOString(),accepted:true,payload:{messageId:message.id}});store.emit('conversation.queued',{messageId:message.id});return c.json(message,200);});
 app.openapi(createRoute({method:'get',path:'/api/v1/knowledge',request:{query:z.object({q:z.string().optional()})},responses:response}),c=>c.json(store.searchKnowledge(c.req.valid('query').q??'',{limit:100}),200));
 app.get('/api/v1/knowledge/:id',async(c,next)=>{if(c.req.query('format')==='markdown')return c.text(store.readKnowledge(c.req.param('id')).content);await next();});
 app.openapi(createRoute({method:'get',path:'/api/v1/knowledge/{id}',request:{params:z.object({id:z.string()})},responses:response}),c=>c.json(store.readKnowledge(c.req.valid('param').id),200));
 app.get('/api/v1/artifacts/:id/content',async c=>{const artifact=store.need('artifacts',c.req.param('id'));if(artifact.kind==='commit'){const project=broker.workspaces.artifact(store.need('projects',artifact.projectId!),artifact);const diff=await broker.workspaces.readDiff(project,artifact.baseCommit??project.baseCommit!,artifact.identity);return c.text(diff);}const path=artifact.uri.replace(/^file:\/\//,'');let safe:string;if(artifact.kind==='release-package')safe=safeChild(join(store.dataRoot,'releases',artifact.id),path);else try{safe=safeChild(join(store.dataRoot,'workspaces'),path);}catch{safe=safeChild(join(store.dataRoot,'vault'),path);}return c.text(readFileSync(safe,'utf8').slice(0,1_000_000));});
 app.openapi(createRoute({method:'post',path:'/api/v1/backup',responses:response}),c=>c.json(store.backup(),200));
 app.openapi(createRoute({method:'post',path:'/api/v1/restore',request:{body:{required:true,content:{'application/json':{schema:z.object({path:z.string().min(1)}).strict()}}}},responses:response}),async c=>{if(!['paused','stopped'].includes(store.company.state))throw new DomainError('pause_required','Pause or stop before restore.',409);await scheduler.pause(true);return c.json(store.restore(c.req.valid('json').path),200);});
 app.openapi(createRoute({method:'get',path:'/api/v1/doctor',responses:response}),async c=>c.json(await doctor(store,runtime,broker),200));
 app.get('/api/v1/runs/:id/inspection',c=>{const run=store.need('runs',c.req.param('id'));return c.json({run,assignment:store.need('assignments',run.assignmentId),employee:store.need('employees',run.employeeId).name,...readInspection(store.dataRoot,run.id)});});
 app.post('/api/v1/runs/:id/inspection/preserve',c=>{const run=store.need('runs',c.req.param('id'));if(run.status!=='failed')throw new DomainError('invalid_run','Only failed runs can be selected for extended diagnostics');const capture=readInspection(store.dataRoot,run.id);if(!capture.available)throw new DomainError('unavailable','Diagnostic capture is unavailable',404);writePrivate(`${inspectionPath(store.dataRoot,run.id)}.selected`,new Date().toISOString());return c.json({selected:true,maximumDays:30});});
 app.get('/api/v1/events',c=>{const requested=c.req.header('last-event-id')??c.req.query('after')??'0';const after=/^\d+$/.test(requested)?Number(requested):0;return streamSSE(c,async stream=>{let closed=false;let chain=Promise.resolve();const write=(event:any)=>{chain=chain.then(async()=>{if(!closed)await stream.writeSSE({id:String(event.id),event:'message',data:JSON.stringify(event)});}).catch(()=>{closed=true;});};const listener=(event:any)=>write(event);store.events.on('event',listener);for(const event of store.eventLog(after,2000))write(event);const keepalive=setInterval(()=>{chain=chain.then(async()=>{if(!closed)await stream.writeSSE({event:'heartbeat',data:JSON.stringify({at:new Date().toISOString()})});}).catch(()=>{closed=true;});},15000);await new Promise<void>(resolve=>{stream.onAbort(()=>{closed=true;clearInterval(keepalive);store.events.off('event',listener);resolve();});});});});
 app.doc('/api/v1/openapi.json',{openapi:'3.1.0',info:{title:'OpenCorp Owner API',version:'0.1.0',description:'Single authenticated loopback backend. No worker credential authorizes Owner routes.'}});
 app.get('/api/v1/openapi',c=>c.redirect('/api/v1/openapi.json'));
 app.get('*',serveStatic({root:join(sourceRoot,'dist/web')}));app.get('*',serveStatic({path:join(sourceRoot,'dist/web/index.html')}));
 return app;
}
export function workerApp(broker:CorporateBroker,getHost:()=>string){const app=new OpenAPIHono();app.onError((e,c)=>c.json({jsonrpc:'2.0',id:null,error:{code:-32000,message:redact(e.message)}},e instanceof DomainError?e.status as any:500));app.all('/mcp/:runId',async c=>{
 if(c.req.header('host')!==getHost()||c.req.header('origin'))throw new DomainError('origin_denied','Worker transport is restricted to its run gateway.',403);
 if(c.req.method==='GET'||c.req.method==='DELETE')return c.body(null,405);if(c.req.method!=='POST')return c.body(null,405);
 const body=await c.req.json();const token=c.req.header('authorization')?.replace(/^Bearer /,'')??'';const actor=broker.actor(c.req.param('runId'),token,false);const run=broker.store.need('runs',c.req.param('runId'));
 if(body.method==='notifications/initialized'||body.method==='notifications/cancelled')return c.body(null,202);
 let result:any;
 if(body.method==='initialize')result={protocolVersion:body.params?.protocolVersion??'2025-03-26',capabilities:{tools:{listChanged:false}},serverInfo:{name:'OpenCorp scoped corporate broker',version:'0.1.0'}};
 else if(body.method==='ping')result={};else if(body.method==='tools/list')result={tools:broker.toolsFor(actor)};
 else if(body.method==='tools/call'){
  const session=c.req.header('x-opencorp-session');if(!run.sessionId||session!==run.sessionId)throw new DomainError('session_mismatch','Corporate tool call is not bound to the active runtime session.',403);
  try{const output=await broker.call(actor,body.params?.name,body.params?.arguments??{});result=output&&typeof output==='object'&&Array.isArray(output.content)?output:{content:[{type:'text',text:redact(typeof output==='string'?output:JSON.stringify(output))}]};}catch(error){result={isError:true,content:[{type:'text',text:redact(`${error instanceof DomainError?error.code:'tool_error'}: ${String(error)}`)}]};}
 }else return c.json({jsonrpc:'2.0',id:body.id,error:{code:-32601,message:'Method not supported'}},200);
 return c.json({jsonrpc:'2.0',id:body.id,result},200);
 });return app;}
export function tokenFingerprint(token:string){return createHash('sha256').update(token).digest('hex').slice(0,8);}
