import type {IncomingMessage} from 'node:http';
import type {ProviderId,ProviderTestResult} from '../core/provider-status.js';
/** Two synthetic requests, one inert local function, no employee/company content. */
export async function testProvider(provider:ProviderId,modelId:string,infer:(body:Record<string,unknown>,signal:AbortSignal)=>Promise<IncomingMessage>,signal:AbortSignal):Promise<ProviderTestResult>{
 const started=Date.now(),result:ProviderTestResult={provider,modelId,status:'failed',startedAt:new Date(started).toISOString(),finishedAt:'',responsePassed:false,toolPassed:false,requests:0,latencyMs:0,httpStatuses:[]};
 async function request(messages:any[],tools?:any[],final=false){
  signal.throwIfAborted();result.requests++;const response=await infer({messages,max_tokens:256,temperature:0,...(provider==='zai'?(tools&&!final?{tools,tool_choice:'auto'}:{}):(tools?{tools,tool_choice:final?'none':{type:'function',function:{name:'add_numbers'}}}:{tool_choice:'none'}))},signal);result.httpStatuses.push(response.statusCode??0);
  const headers:Record<string,string>={};for(const key of ['x-ratelimit-limit','x-ratelimit-remaining','x-ratelimit-reset','x-ratelimit-limit-requests','x-ratelimit-remaining-requests','x-ratelimit-limit-tokens','x-ratelimit-remaining-tokens']){const value=response.headers[key];if(typeof value==='string'&&/^\d{1,16}$/.test(value)&&Number.isSafeInteger(Number(value)))headers[key]=value;}for(const key of ['x-ratelimit-reset-requests','x-ratelimit-reset-tokens']){const value=response.headers[key];if(typeof value==='string'&&value.length<=40&&/^(?:\d+(?:\.\d+)?h)?(?:\d+(?:\.\d+)?m)?(?:\d+(?:\.\d+)?s)?$/.test(value)&&value)headers[key]=value;}if(Object.keys(headers).length)result.quotaHeaders=headers;
  if(response.statusCode!==200){response.destroy();throw new Error('http_failure');}
  let buffer='',bytes=0,content='',finish='',call:any;const stop=()=>response.destroy(new Error('timeout'));signal.addEventListener('abort',stop,{once:true});
  try{signal.throwIfAborted();for await(const chunk of response){signal.throwIfAborted();bytes+=chunk.length;if(bytes>65536)throw new Error('response_bound');buffer+=chunk.toString();let end;while((end=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,end).trim();buffer=buffer.slice(end+1);if(!line.startsWith('data:')||line.slice(5).trim()==='[DONE]')continue;const data=JSON.parse(line.slice(5));for(const choice of data.choices??[]){const delta=choice.delta??{};if(typeof delta.content==='string')content+=delta.content;if(choice.finish_reason)finish=choice.finish_reason;for(const part of delta.tool_calls??[]){if(part.index!==undefined&&part.index!==0)throw new Error('unexpected_tool');if(!call)call={id:'',type:'function',function:{name:'',arguments:''}};if(part.id){if(call.id&&call.id!==part.id)throw new Error('unexpected_tool');call.id=part.id;}if(part.function?.name)call.function.name+=part.function.name;if(part.function?.arguments)call.function.arguments+=part.function.arguments;if(part.extra_content)call.extra_content=part.extra_content;}}}}
  }finally{signal.removeEventListener('abort',stop);response.destroy();}if(!['stop','tool_calls'].includes(finish))throw new Error('incomplete_response');return {content,call};
 }
 try{
  const messages:any[]=[{role:'user',content:'Call add_numbers with a=2 and b=3. After receiving the result, reply exactly READY 5.'}];
  const tools=[{type:'function',function:{name:'add_numbers',description:'Add two integers locally.',parameters:{type:'object',properties:{a:{type:'integer'},b:{type:'integer'}},required:['a','b'],additionalProperties:false}}}];const first=await request(messages,tools);
  const call=first.call,args=JSON.parse(call?.function.arguments??'null');if(!call?.id||call.function.name!=='add_numbers'||JSON.stringify(Object.keys(args??{}).sort())!=='["a","b"]'||args.a!==2||args.b!==3)throw new Error('tool_mismatch');result.toolPassed=true;
  messages.push({role:'assistant',content:null,tool_calls:[call]},{role:'tool',tool_call_id:call.id,content:JSON.stringify({result:args.a+args.b})});const second=await request(messages,tools,true);result.responsePassed=!second.call&&second.content.trim()==='READY 5';if(!result.responsePassed)throw new Error('response_mismatch');result.status='passed';
 }catch{result.errorCode=signal.aborted?'test_timeout':result.httpStatuses.at(-1)===429?'rate_limited':'test_failed';}
 result.finishedAt=new Date().toISOString();result.latencyMs=Date.now()-started;return result;
}
