import {afterEach,beforeEach,describe,expect,it} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {CompanyStore} from '../src/storage/store.js';
import {Scheduler,managementOutcome} from '../src/scheduler/scheduler.js';
import {CorporateBroker,brokerTools} from '../src/tools/broker.js';
import type {LocalRuntime} from '../src/runtime/index.js';
import type {Actor,Assignment,Employee,Artifact} from '../src/core/types.js';

// Actual isolated domain/broker records; mocked receipts are not product proof.
const owner={kind:'owner'} as const,model='wlkr-management-qwen3.8-27b-q4-k-m:latest',criterion='Exact original outcome';
let root:string,store:CompanyStore,broker:CorporateBroker,manager:Employee,worker:Employee,project:any,task:Assignment,managerActor:Extract<Actor,{kind:'employee'}>;
function actor(employee:Employee,assignment:Assignment){const run=store.put('runs',{employeeId:employee.id,assignmentId:assignment.id,modelId:model,policyRevision:store.policy.revision,workspace:root,sessionId:randomUUID(),status:'running',heartbeatAt:new Date().toISOString(),leaseUntil:new Date(Date.now()+60000).toISOString(),tokenRevoked:false});return {kind:'employee',employeeId:employee.id,runId:run.id,policyRevision:store.policy.revision} as const;}
function assigned(employee:Employee,kind='management',payload:any={},acceptance=[criterion]){return store.command(owner,{type:'assignment.create',employeeId:employee.id,supervisorId:manager.id,projectId:project.id,kind,title:'Finite fixture task',instructions:'Preserve original criterion',acceptance,payload});}
function declare(source='artifact',extra:any={}){return store.command(managerActor,{type:'assignment.update',assignmentId:task.id,completionRequirements:[{criterion,source,...extra}],rationale:'Actual meaning requires this explicit evidence kind'});}
function artifact(sourceTask=task){const author=actor(worker,sourceTask),identity=randomUUID(),checks=[{source:'canonical-verifier',identity,status:'passed'}];const output=store.command(author,{type:'artifact.record',kind:'commit',identity,uri:'fixture://commit',summary:'Useful partial improvement',checks});return store.update('artifacts',output.id,{verification:{passed:true,identity,receiptId:randomUUID()}}) as Artifact;}
function review(output:Artifact,coverage?:any[],supplemental=false){const a=assigned(manager,'review',{artifactId:output.id}),reviewer=actor(manager,a);return {reviewer,assignment:a,record:()=>store.command(reviewer,{type:'review.record',artifactId:output.id,artifactIdentity:output.identity,verdict:'approved',rationale:'Actual independently inspected source is ready; future outcomes are not implied',checks:output.checks,...(coverage?{assignmentAcceptance:coverage}:{}),...(supplemental?{supplementalAcceptance:true}:{})})};}
const coverage=(source='artifact',extra:any={})=>[{criterion,source,evidence:'Exact independent evidence for original condition',...extra}];
const proof=(output:Artifact,type='artifact')=>[{criterion,rationale:'Observed retained source',sources:[{type,id:output.id}]}];
function complete(output:Artifact,type='artifact',by:Actor=managerActor){return store.command(by,{type:'assignment.update',assignmentId:task.id,status:'completed',completionEvidence:proof(output,type),rationale:'Confirm exact independently reviewed observed outcomes'});}
function delivered(output:Artifact){return {artifactId:output.id,identity:output.identity,state:'merged',prNumber:4,prUrl:'https://github.com/fixture/product/pull/4',mergeCommit:'merge-fixture',defaultBranchHead:'default-fixture',deliveredAt:new Date().toISOString()};}
beforeEach(()=>{root=mkdtempSync(join(tmpdir(),'opencorp-assignment-completion-'));store=new CompanyStore(root);store.bootstrap();broker=new CorporateBroker(store,root);store.put('models',{name:model,local:true,available:true,artifactIdentity:'fixture-only'});store.command(owner,{type:'control',action:'start'});manager=store.list('employees').find(e=>store.level(e.id)==='ceo')!;const position=store.command(owner,{type:'position.create',title:'Author',level:'worker',responsibilities:'Finite actual work'});worker=store.command(owner,{type:'employee.hire',name:'Fixture author',positionId:position.id,homeManagerId:manager.id,modelId:model});project=store.command(owner,{type:'project.create',name:'Finite project',productId:store.list('products')[0].id,outcome:'Actual outcome',acceptance:[criterion],supervisorId:manager.id,rationale:'Isolated completion fixture'});managerActor=actor(manager,assigned(manager));task=assigned(worker,'implementation');});
afterEach(async()=>{await broker.cancel();store.close();rmSync(root,{recursive:true,force:true});});

describe('artifact readiness and original assignment completion',()=>{
 it('preserves useful approval without inventing completion for an untyped legacy criterion',()=>{
  const output=artifact(),approved=review(output).record();expect(store.hasApprovedArtifact(task.id,output.identity)).toBe(true);expect(store.need('assignments',task.id)).toMatchObject({status:'awaiting_review',acceptance:[criterion],approvedArtifact:{reviewId:approved.id}});expect(store.need('assignments',task.id).completedAt).toBeUndefined();expect(()=>complete(output)).toThrow(/explicitly declare/);expect(()=>complete(output,'artifact',owner)).toThrow(/explicitly declare/);expect(store.need('reviews',approved.id)).toEqual(approved);
 });
 it('requires exact declared criteria and rejects invented replacement criteria',()=>{
  expect(()=>store.command(managerActor,{type:'assignment.update',assignmentId:task.id,completionRequirements:[{criterion:'Invented leak/docs criterion',source:'artifact'}],rationale:'Wrong scope'})).toThrow(/exact criterion/);
  declare();const output=artifact();expect(()=>review(output,coverage('artifact',{criterion:'Invented scope'})).record()).toThrow(/exactly match/);expect(store.list('reviews')).toHaveLength(0);
 });
 it('allows only audited managerial once-only declarations, never a reviewer downgrade',()=>{
  const declared=declare('delivery',{authorship:'external'});expect(declared.requirementsDeclaration).toMatchObject({actorId:manager.id,runId:managerActor.runId});
  expect(()=>declare('artifact')).toThrow(/cannot be weakened/);expect(declare('delivery',{authorship:'external'}).requirementsDeclaration).toEqual(declared.requirementsDeclaration);
  const output=artifact(),r=review(output);expect(()=>store.command(r.reviewer,{type:'assignment.update',assignmentId:task.id,completionRequirements:declared.completionRequirements,rationale:'Reviewer cannot declare'})).toThrow(/reviewer cannot declare/);
  expect(()=>store.command(actor(worker,task),{type:'assignment.update',assignmentId:task.id,completionRequirements:declared.completionRequirements,rationale:'Author authority'})).toThrow();
 });
 it('completes only through current supervisor evidence and then releases dependencies',()=>{
  declare();const output=artifact(),r=review(output,coverage());r.record();const waiter=store.command(owner,{type:'assignment.create',employeeId:worker.id,supervisorId:manager.id,projectId:project.id,kind:'management',title:'Dependent work',instructions:'Wait',acceptance:['Actual successor'],dependencies:[task.id]});
  for(const run of store.list('runs'))store.update('runs',run.id,{status:'succeeded',tokenRevoked:true});expect(store.claimNext({assignmentId:waiter.id})).toBeUndefined();
  managerActor=actor(manager,assigned(manager));const finished=complete(output);expect(finished.status).toBe('completed');expect(finished.completion).toMatchObject({runId:managerActor.runId,acceptance:[criterion]});expect(finished.completionEvidence[0].sources[0]).toMatchObject({identity:output.identity});store.update('runs',managerActor.runId,{status:'succeeded',tokenRevoked:true});expect(store.claimNext({assignmentId:waiter.id})?.assignmentId).toBe(waiter.id);
 });
 it('does not let the reviewer complete even correctly covered original work',()=>{declare();const output=artifact(),r=review(output,coverage());r.record();expect(()=>complete(output,'artifact',r.reviewer)).toThrow(/separately confirms/);expect(store.need('assignments',task.id).status).toBe('awaiting_review');});
 it('requires exact independent coverage even for Owner and passing artifact checks',()=>{declare();const output=artifact();review(output).record();expect(()=>complete(output)).toThrow(/explicitly map/);expect(()=>complete(output,'artifact',owner)).toThrow(/explicitly map/);});
 it('keeps delivery criteria unmet before actual confirmed merge and rejects kind downgrade',()=>{
  declare('delivery');const output=artifact();review(output,coverage('delivery')).record();expect(()=>complete(output,'artifact')).toThrow(/immutable declared/);expect(()=>complete(output,'delivery')).toThrow(/observed exact-artifact merge/);
  store.update('projects',project.id,{delivery:{...delivered(output),defaultBranchHead:null}});expect(()=>complete(output,'delivery')).toThrow(/default-branch ancestry/);store.update('projects',project.id,{delivery:delivered(output)});expect(complete(output,'delivery').status).toBe('completed');
 });
 it('completes explicitly blocked original work when its actual required provider evidence later arrives',()=>{declare('delivery');const output=artifact();review(output,coverage('delivery')).record();store.command(managerActor,{type:'assignment.update',assignmentId:task.id,status:'blocked',blockedReason:'Actual provider merge remains pending',rationale:'Preserve unfinished acceptance'});expect(()=>complete(output,'delivery')).toThrow(/observed exact-artifact merge/);store.update('projects',project.id,{delivery:delivered(output)});expect(complete(output,'delivery').status).toBe('completed');});
 it('never substitutes employee-authored maintenance for required external PR authorship',()=>{declare('delivery',{authorship:'external'});const output=artifact();expect(()=>review(output,coverage('delivery',{authorship:'external'})).record()).toThrow(/external PR candidate/);review(output).record();store.update('projects',project.id,{delivery:delivered(output)});expect(()=>complete(output,'delivery')).toThrow(/external PR candidate/);});
 it('supports an explicitly linked external candidate without rewriting the original scope',()=>{
  declare('delivery',{authorship:'external'});const original=store.need('assignments',task.id),child=assigned(worker,'implementation',{sourceAssignmentId:task.id});const output=artifact(child),source={repository:'fixture/product',number:4,url:'https://github.com/fixture/product/pull/4',authorLogin:'external-contributor',baseRef:'main',baseSha:'base',headRepository:'contributor/product',headRef:'fix',headSha:output.identity,observedAt:new Date().toISOString()},workspace={workspace:'fixture-candidate',gitDir:'fixture-git',mirror:'fixture-mirror',branch:'candidate',baseCommit:'base'};
  store.update('products',project.productId,{binding:{repository:source.repository}});store.update('assignments',child.id,{payload:{sourceAssignmentId:task.id,pullRequest:{number:4,headSha:source.headSha}},pullRequestCandidate:{assignmentId:child.id,source,workspace}});const imported=store.update('artifacts',output.id,{sourcePullRequest:source,reviewWorkspace:workspace});store.update('assignments',task.id,{status:'awaiting_review'});
  review(imported,coverage('delivery',{assignmentId:task.id,authorship:'external'})).record();store.update('projects',project.id,{delivery:{...delivered(imported),source:'existing-pr'}});expect(complete(imported,'delivery').status).toBe('completed');expect(store.need('assignments',task.id).acceptance).toEqual(original.acceptance);expect(store.need('assignments',task.id).payload).toEqual(original.payload);
 });
 it('denies unrelated same-project artifact coverage and incomplete declarations',()=>{expect(()=>store.command(managerActor,{type:'assignment.update',assignmentId:task.id,completionRequirements:[],rationale:'Omitted criterion'})).toThrow(/every exact/);declare();const unrelated=assigned(worker,'implementation'),output=artifact(unrelated);expect(()=>review(output,coverage('artifact',{assignmentId:task.id})).record()).toThrow(/explicit same-project/);});
 it('allows later supplemental coverage for approved but incomplete work without rewriting its review',()=>{declare();const output=artifact(),first=review(output).record(),snapshot=structuredClone(first);const later=review(output,coverage(),true).record();expect(later.supplementalAcceptance).toBe(true);expect(store.need('reviews',first.id)).toEqual(snapshot);expect(store.need('assignments',task.id).status).toBe('awaiting_review');expect(complete(output).status).toBe('completed');});
 it('requires declared exact release version and observed publication receipt',()=>{expect(()=>declare('release')).toThrow(/release version/);declare('release',{version:'1.2.3'});const output=artifact();expect(()=>review(output,coverage('release',{version:'1.2.4'})).record()).toThrow(/exactly match/);review(output,coverage('release',{version:'1.2.3'})).record();const release=store.put('artifacts',{projectId:project.id,sourceArtifactId:output.id,kind:'release-package',identity:'digest',version:'1.2.3',releaseState:'ready'});expect(()=>complete(release,'release')).toThrow(/observed published provider/);});
 it('audits unsupported legacy completion once, retains review/raw history and refuses premature dependencies',()=>{
  const output=artifact(),approved=review(output).record(),completedAt='2026-09-01T00:00:00.000Z';store.update('assignments',task.id,{status:'completed',completedAt});const before=store.need('assignments',task.id);expect(store.assignmentCompleted(before)).toBe(false);expect(store.reconcileAssignmentCompletions()).toHaveLength(1);expect(store.reconcileAssignmentCompletions()).toEqual([]);const after=store.need('assignments',task.id);expect(after.status).toBe('awaiting_review');expect(after.completedAt).toBeUndefined();expect(after.completionHistory.at(-1)).toMatchObject({status:'completed',completedAt,actorId:'system'});expect(after.acceptance).toEqual(before.acceptance);expect(store.need('reviews',approved.id)).toEqual(approved);
 });
 it('preserves valid observed completion and rejects reducing its evidence during later updates',()=>{declare();const output=artifact();review(output,coverage()).record();const completed=complete(output);expect(()=>store.command(managerActor,{type:'assignment.update',assignmentId:task.id,completionEvidence:[],rationale:'Remove actual evidence'})).toThrow(/Every original acceptance/);expect(store.reconcileAssignmentCompletions()).toEqual([]);expect(store.need('assignments',task.id)).toEqual(completed);});
 it('schedules one autonomous company-workspace followup without blocking independent delivery',()=>{
  const output=artifact();review(output).record();const scheduler=new Scheduler(store,{} as LocalRuntime,broker,'http://localhost');for(const run of store.list('runs'))store.update('runs',run.id,{status:'succeeded',tokenRevoked:true});
  (scheduler as any).reconcileOrganization();(scheduler as any).reconcileOrganization();const followups=store.list('assignments').filter(a=>a.schedulerKey?.startsWith(`acceptance:${task.id}:`));expect(followups).toHaveLength(1);expect(followups[0]).toMatchObject({projectId:null,employeeId:manager.id,payload:{acceptanceAssignmentId:task.id,sourceProjectId:project.id}});expect(store.list('assignments').some(a=>a.schedulerKey===`deliver:${output.id}`)).toBe(true);
  const reviewer=actor(manager,followups[0]),run=store.need('runs',reviewer.runId);expect(managementOutcome(store,followups[0],run).passed).toBe(false);store.command(reviewer,{type:'knowledge.write',scope:'company',title:'Unrelated prose',content:'Claim completion without evidence',source:'fixture'});expect(managementOutcome(store,followups[0],store.need('runs',run.id)).passed).toBe(false);
  store.command(reviewer,{type:'assignment.update',assignmentId:task.id,completionRequirements:[{criterion,source:'delivery'}],rationale:'Explicit reviewed meaning'});expect(managementOutcome(store,followups[0],store.need('runs',run.id)).passed).toBe(true);
 });
 it.each(['company-scope','author'])('does not let a malformed legacy %s review prevent recovery',variant=>{const output=artifact();review(output).record();for(const run of store.list('runs'))store.update('runs',run.id,{status:'succeeded',tokenRevoked:true});store.put('assignments',{employeeId:variant==='author'?worker.id:manager.id,projectId:variant==='company-scope'?null:project.id,kind:'review',status:'queued',payload:{artifactId:output.id}});const scheduler=new Scheduler(store,{} as LocalRuntime,broker,'http://localhost');(scheduler as any).reconcileAcceptance();expect(store.list('assignments').some(a=>a.schedulerKey?.startsWith(`acceptance:${task.id}:`))).toBe(true);});
 it('routes shared-staffing acceptance to existing common management with actual broker evidence and review authority',async()=>{
  const hireManager=(name:string)=>{const position=store.command(owner,{type:'position.create',title:name,level:'manager',responsibilities:'Supervise shared work'});return store.command(owner,{type:'employee.hire',name,positionId:position.id,homeManagerId:manager.id,modelId:model});};
  const taskManager=hireManager('Task manager'),homeManager=hireManager('Author home manager');store.command(owner,{type:'employee.reassign',employeeId:worker.id,homeManagerId:homeManager.id});store.command(owner,{type:'assignment.update',assignmentId:task.id,supervisorId:taskManager.id});const output=artifact();review(output).record();for(const run of store.list('runs'))store.update('runs',run.id,{status:'succeeded',tokenRevoked:true});
  const scheduler=new Scheduler(store,{} as LocalRuntime,broker,'http://localhost');(scheduler as any).reconcileAcceptance();const followup=store.list('assignments').find(a=>a.schedulerKey?.startsWith(`acceptance:${task.id}:`))!;expect(followup).toMatchObject({employeeId:manager.id,projectId:null});expect(store.need('assignments',task.id).supervisorId).toBe(taskManager.id);const by=actor(manager,followup);
  await expect(broker.call(by,'company_detail',{collection:'assignments',id:task.id})).resolves.toMatchObject({record:{id:task.id}});await expect(broker.call(by,'company_detail',{collection:'artifacts',id:output.id,view:'record'})).resolves.toMatchObject({record:{id:output.id}});
  await broker.call(by,'company_command',{command:{type:'assignment.update',assignmentId:task.id,completionRequirements:[{criterion,source:'artifact'}],rationale:'Explicit common-management declaration'}});
  await broker.call(by,'create_assignment',{employeeId:taskManager.id,projectId:project.id,kind:'review',title:'Review exact coverage',instructions:'Inspect original declared criterion',acceptance:['Retain actual coverage'],payload:{artifactId:output.id}});expect(managementOutcome(store,followup,store.need('runs',by.runId)).passed).toBe(true);
 });
 it('does not count a review created then cancelled or blocked as actionable acceptance recovery',async()=>{
  declare();const output=artifact();review(output).record();for(const run of store.list('runs'))store.update('runs',run.id,{status:'succeeded',tokenRevoked:true});const scheduler=new Scheduler(store,{} as LocalRuntime,broker,'http://localhost');(scheduler as any).reconcileAcceptance();const followup=store.list('assignments').find(a=>a.schedulerKey?.startsWith(`acceptance:${task.id}:`))!,by=actor(manager,followup);
  const created=await broker.call(by,'create_assignment',{employeeId:manager.id,projectId:project.id,kind:'review',title:'Coverage review',instructions:'Independently inspect exact source',acceptance:['Exact criterion coverage'],payload:{artifactId:output.id}});expect(managementOutcome(store,followup,store.need('runs',by.runId)).passed).toBe(true);
  await broker.call(by,'company_command',{command:{type:'assignment.update',assignmentId:created.id,status:'cancelled',rationale:'No actual reviewer remains'}});expect(managementOutcome(store,followup,store.need('runs',by.runId)).passed).toBe(false);
 });
 it.each(['cancelled','blocked'] as const)('reconciles a later %s coverage review without retrying it or duplicating staffing recovery',async status=>{
  declare();const output=artifact();review(output).record();for(const run of store.list('runs'))store.update('runs',run.id,{status:'succeeded',tokenRevoked:true});
  const scheduler=new Scheduler(store,{} as LocalRuntime,broker,'http://localhost');(scheduler as any).reconcileAcceptance();const followup=store.list('assignments').find(a=>a.schedulerKey?.startsWith(`acceptance:${task.id}:`))!;
  const start=(assignment:Assignment)=>{const run=store.claimNext({assignmentId:assignment.id,workspace:root})!;expect(run).toBeDefined();store.bindSession(run.id,randomUUID());return {kind:'employee',employeeId:manager.id,runId:run.id,policyRevision:store.policy.revision} as const;};
  const by=start(followup),created=await broker.call(by,'create_assignment',{employeeId:manager.id,projectId:project.id,kind:'review',title:'Delegated coverage review',instructions:'Independently inspect the retained criterion',acceptance:['Exact criterion coverage'],payload:{artifactId:output.id}});
  const outcome=managementOutcome(store,followup,store.need('runs',by.runId));expect(outcome.passed).toBe(true);store.finishRun(by.runId,{status:'succeeded',managementResult:{summary:outcome.summary}});const completed=store.need('assignments',followup.id),original=store.need('assignments',task.id);expect(completed.status).toBe('completed');
  (scheduler as any).reconcileAcceptance();expect(store.list('assignments').filter(a=>a.schedulerKey?.startsWith(`acceptance:${task.id}:`))).toHaveLength(1);
  const later=start(assigned(manager));await broker.call(later,'company_command',{command:{type:'assignment.update',assignmentId:created.id,status,blockedReason:'The delegated reviewer is unavailable',rationale:'Preserve the review; management must choose the next disposition'}});store.finishRun(later.runId,{status:'succeeded'});const lostReview=store.need('assignments',created.id);
  (scheduler as any).reconcileAcceptance();const restarted=new Scheduler(store,{} as LocalRuntime,broker,'http://localhost');(restarted as any).reconcileAcceptance();
  const followups=store.list('assignments').filter(a=>a.schedulerKey?.startsWith(`acceptance:${task.id}:`));expect(followups).toHaveLength(status==='cancelled'?2:1);
  if(status==='cancelled'){const recovery=followups.find(a=>a.id!==followup.id)!;expect(recovery).toMatchObject({status:'queued',kind:'management',projectId:null,employeeId:manager.id,payload:{acceptanceAssignmentId:task.id,sourceProjectId:project.id}});expect(recovery.schedulerKey).not.toBe(completed.schedulerKey);}
  expect(store.need('assignments',followup.id)).toEqual(completed);expect(store.need('assignments',task.id)).toEqual(original);expect(store.need('assignments',created.id)).toEqual(lostReview);expect(store.list('runs').some(run=>run.assignmentId===created.id)).toBe(false);expect(store.list('assignments').filter(a=>a.kind==='review'&&a.payload?.artifactId===output.id)).toHaveLength(2);expect(store.list('actions')).toHaveLength(0);
 });
 it('advertises the actual nested requirements, coverage and supervisor completion wire',async()=>{
  const command:any=brokerTools.find(t=>t.name==='company_command')!.inputSchema,branch=command.properties.command.anyOf.find((b:any)=>b.properties.type.enum[0]==='assignment.update');expect(branch.properties.completionRequirements.items.properties.authorship.enum).toEqual(['external']);expect(branch.properties.completionEvidence.items.properties.sources.items.properties.type.enum).toEqual(['artifact','delivery','release']);
  const r:any=brokerTools.find(t=>t.name==='review_work')!.inputSchema;expect(r.properties.assignmentAcceptance.items.properties.assignmentId.type).toBe('string');
  await broker.call(managerActor,'company_command',{command:{type:'assignment.update',assignmentId:task.id,completionRequirements:[{criterion,source:'artifact'}],rationale:'Actual broker declaration'}});const output=artifact();review(output,coverage()).record();await broker.call(managerActor,'company_command',{command:{type:'assignment.update',assignmentId:task.id,status:'completed',completionEvidence:proof(output),rationale:'Actual broker completion'}});expect(store.assignmentCompleted(store.need('assignments',task.id))).toBe(true);
 });
});
