import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {CompanyStore} from '../src/storage/store.js';
import {CorporateBroker} from '../src/tools/broker.js';
import {Scheduler,managementOutcome} from '../src/scheduler/scheduler.js';
import {deliveryCommunicationKey} from '../src/core/delivery.js';
import {checked} from '../src/tools/process.js';
import type {Artifact,Assignment,DeliveryReceipt,Project,EmployeeRun} from '../src/core/types.js';
import type {LocalRuntime} from '../src/runtime/index.js';

vi.mock('../src/tools/process.js',async original=>({...await original<typeof import('../src/tools/process.js')>(),checked:vi.fn()}));
const provider=vi.mocked(checked),owner={kind:'owner'} as const,repo='fixture-owner/product',model='wlkr-management-qwen3.8-27b-q4-k-m:latest';
let root:string,store:CompanyStore,broker:CorporateBroker,scheduler:Scheduler,project:Project,artifact:Artifact,receipt:DeliveryReceipt,mergeTask:Assignment,mergeRun:EmployeeRun,sends:string[];
function reconcile(){(scheduler as any).reconcileOrganization();}
function tasks(){return store.list('assignments').filter(a=>a.schedulerKey?.startsWith('delivery-communication:'));}
function claim(task=tasks()[0]){const run=store.claimNext({assignmentId:task.id,workspace:root})!;expect(run).toBeDefined();store.bindSession(run.id,`fixture-session-${run.id}`);return {kind:'employee',employeeId:run.employeeId,runId:run.id,policyRevision:store.policy.revision} as const;}
const input=()=>({kind:'pr_comment',number:receipt.prNumber,content:'The reviewed correction merged. Release and broader project acceptance remain separate.',dedupeKey:'employee-selected-key'});
function reads(override?:(args:string[],options:any)=>Promise<string|undefined>){provider.mockImplementation(async(file,args,options={})=>{if(file!=='gh')throw new Error('No native product work is permitted in this fixture');if(args.includes('POST'))sends.push(String(options.input));const changed=await override?.(args,options);if(changed!==undefined)return changed;if(args.includes('user'))return 'fixture-owner';if(args[1]===`repos/${repo}/pulls/${receipt.prNumber}`)return JSON.stringify({number:receipt.prNumber,html_url:receipt.prUrl,merged:true,head:{sha:artifact.identity},base:{ref:'main',repo:{full_name:repo}},merge_commit_sha:receipt.mergeCommit});if(args.includes('POST'))return JSON.stringify({id:77,html_url:`${receipt.prUrl}#issuecomment-77`});throw new Error(`Unexpected fixture provider read ${args.join(' ')}`);});}
function priorAction(patch:Record<string,unknown>={}){return store.put('actions',{kind:'communication',productId:project.productId!,employeeId:mergeRun.employeeId,runId:mergeRun.id,target:`${repo}/pulls/${receipt.prNumber}`,content:{kind:'pr_comment',number:receipt.prNumber,title:'',body:'Earlier employee-authored merge communication'},dedupeKey:'earlier-task-comment',status:'succeeded',remoteRef:`${receipt.prUrl}#issuecomment-66`,result:{id:66},cost:0,costEvidence:'Fixture observed provider receipt',policyRevision:store.policy.revision,...patch});}
beforeEach(()=>{
 root=mkdtempSync(join(tmpdir(),'opencorp-delivery-communication-'));store=new CompanyStore(root);store.bootstrap();store.put('models',{name:model,local:true,available:true,artifactIdentity:'fixture-model'});store.command(owner,{type:'control',action:'start'});broker=new CorporateBroker(store,root);scheduler=new Scheduler(store,{} as LocalRuntime,broker,'http://localhost');sends=[];
 const manager=store.list('employees').find(e=>store.level(e.id)==='ceo')!,product=store.list('products')[0];store.update('products',product.id,{binding:{repository:repo,defaultBranch:'main'}});
 project=store.command(owner,{type:'project.create',name:'Finite outcome',productId:product.id,outcome:'Actual scoped correction',acceptance:['Separate broader outcome'],supervisorId:manager.id,rationale:'Isolated fixture'});
 const position=store.command(owner,{type:'position.create',title:'Author',level:'worker',responsibilities:'Finite code changes'}),worker=store.command(owner,{type:'employee.hire',name:'Author',positionId:position.id,homeManagerId:manager.id,modelId:model}),original=store.command(owner,{type:'assignment.create',projectId:project.id,employeeId:worker.id,title:'Original unchanged work',instructions:'Retain original acceptance',acceptance:['Original outcome'],kind:'implementation'});store.update('assignments',original.id,{status:'blocked',blockedReason:'Original acceptance still unmet'});
 artifact=store.put('artifacts',{projectId:project.id,assignmentId:original.id,employeeId:worker.id,runId:'fixture-author-run',kind:'commit',identity:'a'.repeat(40),uri:'fixture://source',summary:'Reviewed partial correction',checks:[{source:'canonical-verifier',identity:'a'.repeat(40),status:'passed'}]});store.put('reviews',{artifactId:artifact.id,artifactIdentity:artifact.identity,employeeId:manager.id,runId:'fixture-review-run',verdict:'approved',rationale:'Actual partial source approval',checks:artifact.checks});
 receipt={state:'merged',artifactId:artifact.id,identity:artifact.identity,prNumber:7,prUrl:`https://github.com/${repo}/pull/7`,mergeCommit:'b'.repeat(40),defaultBranchHead:'b'.repeat(40),deliveredAt:'2026-01-01T00:00:00.000Z'};project=store.update('projects',project.id,{delivery:receipt});
 mergeTask=store.command(owner,{type:'assignment.create',projectId:project.id,employeeId:manager.id,title:'Complete checked delivery',instructions:'Merge then communicate actual progress',acceptance:['Observed merge'],kind:'management',payload:{artifactId:artifact.id,mergeReady:true}});mergeTask=store.update('assignments',mergeTask.id,{status:'completed',completedAt:'2026-01-01T00:01:00.000Z',schedulerKey:`merge-ready:${artifact.id}:${artifact.identity}`});mergeRun=store.put('runs',{employeeId:manager.id,assignmentId:mergeTask.id,modelId:model,status:'succeeded',tokenRevoked:true,sessionId:'prior-merge-session',workspace:root,policyRevision:store.policy.revision});reads();
});
afterEach(async()=>{await broker.cancel();store.close();rmSync(root,{recursive:true,force:true});vi.restoreAllMocks();});

describe('durable missing post-merge communication',()=>{
 it('recovers the completed merge with one new employee assignment while preserving its history',()=>{reconcile();reconcile();scheduler=new Scheduler(store,{} as LocalRuntime,broker,'http://localhost');reconcile();expect(tasks()).toHaveLength(1);expect(tasks()[0]).toMatchObject({kind:'management',projectId:project.id,status:'queued',schedulerKey:deliveryCommunicationKey(receipt),payload:{artifactId:artifact.id,artifactIdentity:artifact.identity,mergeCommit:receipt.mergeCommit,prNumber:7}});expect(tasks()[0].instructions).toContain('call communicate');expect(tasks()[0].instructions).toContain('Do not call assignment.update status completed');expect(store.need('assignments',mergeTask.id)).toEqual(mergeTask);expect(store.need('runs',mergeRun.id)).toEqual(mergeRun);expect(store.list('actions')).toEqual([]);expect(provider).not.toHaveBeenCalled();});
 it('requires an actual observed comment; prose, internal messages and self-completion do not satisfy it',async()=>{reconcile();const by=claim(),task=tasks()[0];store.update('runs',by.runId,{text:'The comment was sent.'});await broker.call(by,'company_command',{command:{type:'message.send',content:'Merged and communicated'}});expect(managementOutcome(store,task,store.need('runs',by.runId)).passed).toBe(false);await expect(broker.call(by,'company_command',{command:{type:'assignment.update',assignmentId:task.id,status:'completed',rationale:'Only a claim'}})).rejects.toThrow(/scheduler handles completion/);expect(store.list('actions')).toHaveLength(0);});
 it('sends employee-authored content once and reuses the observed receipt despite changed key or wording',async()=>{reconcile();const by=claim(),task=tasks()[0],sent=await broker.call(by,'communicate',input());expect(sent).toMatchObject({status:'succeeded',artifactId:artifact.id,artifactIdentity:artifact.identity,dedupeKey:deliveryCommunicationKey(receipt),cost:0});expect(JSON.parse(sends[0]).body).toBe(`${input().content}\n\n<!-- opencorp-action:${sent.id} -->`);const repeated=await broker.call(by,'communicate',{...input(),content:'Different later wording',dedupeKey:'attempt-two'});expect(repeated.id).toBe(sent.id);expect(sends).toHaveLength(1);const outcome=managementOutcome(store,task,store.need('runs',by.runId));expect(outcome.passed).toBe(true);store.finishRun(by.runId,{status:'succeeded',managementResult:{summary:outcome.summary}});reconcile();expect(tasks()).toHaveLength(1);expect(tasks()[0].status).toBe('completed');expect(store.need('assignments',mergeTask.id)).toEqual(mergeTask);});
 it.each(['pr','issue'] as const)('does not duplicate existing observed %s communication',kind=>{const action=priorAction(kind==='issue'?{target:`${repo}/issues/4`,content:{kind:'issue_comment',number:4,body:'Observed issue verification'},remoteRef:`https://github.com/${repo}/issues/4#issuecomment-66`}:{});if(kind==='issue')store.update('projects',project.id,{delivery:{...receipt,issueNumber:4,issueEvidenceActionId:action.id}});reconcile();expect(tasks()).toEqual([]);expect(provider).not.toHaveBeenCalled();});
 it.each(['draft','pre-merge','different-task','wrong-product','wrong-pr'] as const)('does not accept %s as observed task-related communication',kind=>{const action=priorAction();if(kind==='draft')store.update('actions',action.id,{status:'prepared',remoteRef:undefined,result:undefined});if(kind==='pre-merge')store.put('actions',{...action,createdAt:'2025-01-01T00:00:00.000Z'});if(kind==='different-task')store.update('assignments',mergeTask.id,{payload:{artifactId:'another-artifact'}});if(kind==='wrong-product')store.update('actions',action.id,{productId:'another-product'});if(kind==='wrong-pr')store.update('actions',action.id,{target:`${repo}/pulls/8`,content:{...action.content,number:8}});reconcile();expect(tasks()).toHaveLength(1);});
 it.each(['target','head','base','merge','identity'] as const)('denies changed %s before dispatch',async changed=>{reconcile();const by=claim();reads(async args=>{if(changed==='identity'&&args.includes('user'))return 'another-owner';if(args[1]!==`repos/${repo}/pulls/7`)return;const live={number:7,html_url:receipt.prUrl,merged:true,head:{sha:artifact.identity},base:{ref:'main',repo:{full_name:repo}},merge_commit_sha:receipt.mergeCommit};if(changed==='head')live.head.sha='wrong';if(changed==='base')live.base.ref='another';if(changed==='merge')live.merge_commit_sha='wrong';return JSON.stringify(live);});await expect(broker.call(by,'communicate',{...input(),...(changed==='target'?{number:8}:{})})).rejects.toThrow();expect(sends).toHaveLength(0);expect(store.list('actions').every(action=>action.status==='prepared')).toBe(true);});
 it('does not dispatch after pause during the fresh PR observation',async()=>{reconcile();const by=claim();reads(async args=>{if(args[1]===`repos/${repo}/pulls/7`)store.command(owner,{type:'control',action:'pause'});return undefined;});await expect(broker.call(by,'communicate',input())).rejects.toThrow();expect(sends).toHaveLength(0);expect(store.list('actions')[0].status).toBe('prepared');});
 it.each(['employee','supervisor','employee-and-project'] as const)('rechecks a changed %s assignment after a deferred PR read',async field=>{
  reconcile();const by=claim(),task=tasks()[0],position=store.command(owner,{type:'position.create',title:'Alternate manager',level:'manager',responsibilities:'Existing scoped management'}),alternate=store.command(owner,{type:'employee.hire',name:'Alternate manager',positionId:position.id,homeManagerId:by.employeeId,modelId:model});
  let entered!:()=>void,release!:()=>void;const waiting=new Promise<void>(resolve=>{entered=resolve;}),released=new Promise<void>(resolve=>{release=resolve;});reads(async args=>{if(args[1]===`repos/${repo}/pulls/7`){entered();await released;}return undefined;});const send=broker.call(by,'communicate',input());await waiting;
  store.command(owner,{type:'assignment.update',assignmentId:task.id,...(field==='supervisor'?{supervisorId:alternate.id}:{employeeId:alternate.id}),rationale:'Actual reassignment while provider metadata is pending'});if(field==='employee-and-project'){store.command(owner,{type:'assignment.update',assignmentId:task.id,supervisorId:alternate.id});store.command(owner,{type:'project.update',projectId:project.id,supervisorId:alternate.id,rationale:'Same new project supervisor'});}
  release();await expect(send).rejects.toThrow(/scope changed/);expect(sends).toHaveLength(0);expect(store.list('actions')).toHaveLength(1);expect(store.list('actions')[0]).toMatchObject({status:'prepared',runId:by.runId});expect(store.need('runs',by.runId).tokenRevoked).toBe(false);
 });
 it('adopts a never-dispatched intent on retry using its original content and stable key',async()=>{reconcile();const by=claim();reads(async args=>args.includes('user')?'wrong-owner':undefined);await expect(broker.call(by,'communicate',input())).rejects.toThrow(/identity/);const prepared=store.list('actions')[0];store.revokeRun(by.runId,'Fixture pause');store.finishRun(by.runId,{status:'interrupted'});const next=claim();reads();const sent=await broker.call(next,'communicate',{...input(),content:'Rewritten words must not replace durable intent',dedupeKey:'new-key'});expect(sent.id).toBe(prepared.id);expect(sent.priorRunIds).toContain(by.runId);expect(JSON.parse(sends[0]).body).toContain(input().content);expect(sends).toHaveLength(1);});
 it('never replays an uncertain send and resolves by the existing provider marker',async()=>{reconcile();const by=claim();reads(async args=>{if(args.includes('POST'))throw new Error('Response lost after provider send');return undefined;});await expect(broker.call(by,'communicate',input())).rejects.toThrow(/uncertain/);const pending=store.list('actions')[0];expect(managementOutcome(store,tasks()[0],store.need('runs',by.runId)).passed).toBe(false);await expect(broker.call(by,'communicate',{...input(),content:'Retry',dedupeKey:'different'})).rejects.toThrow(/reconcile/);expect(sends).toHaveLength(1);reads(async args=>args[1]?.includes('/comments?')?JSON.stringify([{id:77,html_url:`${receipt.prUrl}#issuecomment-77`,body:`Original employee comment\n<!-- opencorp-action:${pending.id} -->`}]):undefined);await broker.github.reconcile(pending.id);const observed=await broker.call(by,'communicate',input());expect(observed.id).toBe(pending.id);expect(observed.status).toBe('succeeded');expect(managementOutcome(store,tasks()[0],store.need('runs',by.runId)).passed).toBe(true);expect(sends).toHaveLength(1);});
 it('preserves uncertain earlier continuation sends and never creates a new intent',async()=>{const earlier=priorAction({status:'uncertain',remoteRef:undefined,result:undefined});reconcile();const by=claim();await expect(broker.call(by,'communicate',input())).rejects.toThrow(earlier.id);expect(store.list('actions')).toHaveLength(1);expect(sends).toHaveLength(0);});
 it('adopts an exact earlier prepared intent under its original key and wording',async()=>{const earlier=priorAction({status:'prepared',remoteRef:undefined,result:undefined});reconcile();const by=claim(),sent=await broker.call(by,'communicate',input());expect(sent).toMatchObject({id:earlier.id,dedupeKey:earlier.dedupeKey,runId:by.runId,artifactId:artifact.id,artifactIdentity:artifact.identity,status:'succeeded',priorRunIds:[mergeRun.id],content:earlier.content});expect(JSON.parse(sends[0]).body).toBe(`${earlier.content.body}\n\n<!-- opencorp-action:${earlier.id} -->`);await broker.call(by,'communicate',{...input(),content:'New wording',dedupeKey:'new-key'});expect(store.list('actions')).toHaveLength(1);expect(sends).toHaveLength(1);expect(store.need('assignments',mergeTask.id)).toEqual(mergeTask);expect(managementOutcome(store,tasks()[0],store.need('runs',by.runId)).passed).toBe(true);});
 it('keeps a mismatched provider comment receipt uncertain through reconciliation',async()=>{reconcile();const by=claim();reads(async args=>args.includes('POST')?JSON.stringify({id:77,html_url:`https://github.com/${repo}/pull/8#issuecomment-77`}):undefined);await expect(broker.call(by,'communicate',input())).rejects.toThrow(/uncertain/);const action=store.list('actions')[0];reads(async args=>args[1]?.includes('/comments?')?JSON.stringify([{id:77,html_url:`https://github.com/${repo}/pull/8#issuecomment-77`,body:`<!-- opencorp-action:${action.id} -->`}]):undefined);await broker.github.reconcile(action.id);expect(store.need('actions',action.id).status).toBe('uncertain');expect(managementOutcome(store,tasks()[0],store.need('runs',by.runId)).passed).toBe(false);expect(sends).toHaveLength(1);});
 it('retains strict receipt reconciliation for an adopted legacy key',async()=>{const earlier=priorAction({status:'prepared',remoteRef:undefined,result:undefined});reconcile();const by=claim();reads(async args=>args.includes('POST')?JSON.stringify({id:77,html_url:`https://github.com/${repo}/pull/8#issuecomment-77`}):undefined);await expect(broker.call(by,'communicate',input())).rejects.toThrow(/uncertain/);expect(store.need('actions',earlier.id)).toMatchObject({artifactId:artifact.id,artifactIdentity:artifact.identity,dedupeKey:earlier.dedupeKey});reads(async args=>args[1]?.includes('/comments?')?JSON.stringify([{id:77,html_url:`https://github.com/${repo}/pull/8#issuecomment-77`,body:`<!-- opencorp-action:${earlier.id} -->`}]):undefined);await broker.github.reconcile(earlier.id);expect(store.need('actions',earlier.id).status).toBe('uncertain');await expect(broker.call(by,'communicate',input())).rejects.toThrow(/reconcile/);expect(sends).toHaveLength(1);});
 it('refuses adoption while the earlier intent owner is still active',async()=>{const earlier=priorAction({status:'prepared',remoteRef:undefined,result:undefined});reconcile();const by=claim();store.update('runs',mergeRun.id,{status:'running',tokenRevoked:false});await expect(broker.call(by,'communicate',input())).rejects.toThrow(/Previous intent owner has not finished/);expect(store.need('actions',earlier.id)).toEqual(earlier);expect(sends).toHaveLength(0);});
 it('rejects caller-supplied reserved reconciliation markers',async()=>{reconcile();const by=claim();await expect(broker.call(by,'communicate',{...input(),content:'<!-- opencorp-action:another-action -->'})).rejects.toThrow(/Reserved action markers/);expect(store.list('actions')).toHaveLength(0);});
 it('retains one independent followup per historical merged artifact',()=>{const older={...receipt,artifactId:'earlier-artifact',identity:'c'.repeat(40),prNumber:3,prUrl:`https://github.com/${repo}/pull/3`,mergeCommit:'d'.repeat(40)};const historical=store.put('artifacts',{...artifact,id:older.artifactId,identity:older.identity,checks:[{source:'canonical-verifier',identity:older.identity,status:'passed'}]});store.put('reviews',{artifactId:historical.id,artifactIdentity:historical.identity,employeeId:mergeRun.employeeId,runId:'old-review-run',verdict:'approved'});store.update('projects',project.id,{deliveryHistory:[older,receipt]});reconcile();expect(tasks()).toHaveLength(2);expect(new Set(tasks().map(task=>task.schedulerKey))).toEqual(new Set([deliveryCommunicationKey(older),deliveryCommunicationKey(receipt)]));});
 it('preserves cancelled followup history instead of automatically retrying it',()=>{reconcile();const task=tasks()[0];store.command(owner,{type:'assignment.update',assignmentId:task.id,status:'cancelled',rationale:'Management chose to defer communication'});const cancelled=store.need('assignments',task.id);reconcile();expect(tasks()).toEqual([cancelled]);});
 it('does not claim completion using a forged communication assignment key',()=>{reconcile();const by=claim(),task=store.update('assignments',tasks()[0].id,{schedulerKey:'delivery-communication:forged'});priorAction();expect(managementOutcome(store,task,store.need('runs',by.runId)).passed).toBe(false);});
});
