import {it,expect,vi} from 'vitest';
import {PassThrough} from 'node:stream';
import {testProvider} from '../src/runtime/provider-test.js';
function response(deltas:any[],status=200){const s=new PassThrough() as any;s.statusCode=status;s.headers={'x-ratelimit-remaining-requests':'3','authorization':'secret'};queueMicrotask(()=>s.end(deltas.map(delta=>'data: '+JSON.stringify({choices:[delta]})+'\n\n').join('')));return s;}
it('executes exactly one inert function roundtrip and retains no text or opaque signature',async()=>{const bodies:any[]=[];const infer=vi.fn(async(body:any)=>{bodies.push(body);return bodies.length===1?response([{delta:{tool_calls:[{id:'call',function:{name:'add_numbers',arguments:'{"a":2,"b":3}'},extra_content:{google:{thought_signature:'opaque'}}}]},finish_reason:'stop'}]):response([{delta:{content:'READY 5'},finish_reason:'stop'}]);});const result=await testProvider('gemini','gemini:fixture',infer,AbortSignal.timeout(1000));expect(result.status).toBe('passed');expect(result.requests).toBe(2);expect(bodies[1].tools).toEqual(bodies[0].tools);expect(bodies[1].tool_choice).toBe('none');expect(bodies[1].messages[1].tool_calls[0].extra_content.google.thought_signature).toBe('opaque');expect(JSON.stringify(result)).not.toMatch(/opaque|READY|secret/);expect(result.quotaHeaders).toEqual({'x-ratelimit-remaining-requests':'3'});});
it('rejects wrong arguments without a second request and retains no upstream failure content',async()=>{const infer=vi.fn(async()=>response([{delta:{tool_calls:[{id:'call',function:{name:'add_numbers',arguments:'{"a":9,"b":3}'}}]},finish_reason:'stop'}]));expect((await testProvider('groq','groq:fixture',infer,AbortSignal.timeout(1000))).status).toBe('failed');expect(infer).toHaveBeenCalledTimes(1);});
it('closes a stream when its signal was aborted before iteration',async()=>{const controller=new AbortController(),stream=new PassThrough() as any;stream.statusCode=200;stream.headers={};const result=await testProvider('groq','groq:fixture',async()=>{controller.abort();return stream;},controller.signal);expect(result.errorCode).toBe('test_timeout');expect(stream.destroyed).toBe(true);});
it('does not retry HTTP429',async()=>{const infer=vi.fn(async()=>response([],429));const result=await testProvider('groq','groq:fixture',infer,AbortSignal.timeout(1000));expect(result.errorCode).toBe('rate_limited');expect(infer).toHaveBeenCalledTimes(1);});

import {LocalRuntime} from '../src/runtime/index.js';
it('allows audited models outside production selection and isolates tests from same-provider work',async()=>{const runtime=new LocalRuntime({dataRoot:'/tmp/unused-provider-test',directFree:{groq:{modelIds:[],readCredentials:async()=>({apiKey:'never exposed',audit:{provider:'groq',modelIds:['groq:audited'],expiresAt:new Date(Date.now()+60000).toISOString()} as any})}}});const rows=await runtime.providerStatus();expect(rows.find(r=>r.id==='groq')?.modelIds).toEqual(['groq:audited']);(runtime as any).activeProviders.set('active','groq');await expect(runtime.testProvider('groq','groq:audited')).rejects.toThrow(/busy/);(runtime as any).activeProviders.clear();const result=await runtime.testProvider('groq','groq:unaudited');expect(result.errorCode).toBe('eligibility_unavailable');expect(result.requests).toBe(0);expect(JSON.stringify(result)).not.toContain('never exposed');});
it('shutdown aborts and awaits a provider diagnostic without inference dispatch replay',async()=>{const runtime=new LocalRuntime({dataRoot:'/tmp/unused-provider-test'});let released=false;(runtime as any).testController=new AbortController();(runtime as any).testDone=new Promise<void>(resolve=>{(runtime as any).testController.signal.addEventListener('abort',()=>{released=true;resolve();});});vi.spyOn((runtime as any).ollama,'stop').mockResolvedValue(undefined);vi.spyOn((runtime as any).microOllama,'stop').mockResolvedValue(undefined);await runtime.stop();expect(released).toBe(true);});
it('uses Z.ai auto tool selection and omits tools after the real result',async()=>{const bodies:any[]=[];const infer=vi.fn(async(body:any)=>{bodies.push(body);return bodies.length===1?response([{delta:{tool_calls:[{id:'call',function:{name:'add_numbers',arguments:'{"a":2,"b":3}'}}]},finish_reason:'tool_calls'}]):response([{delta:{content:'READY 5'},finish_reason:'stop'}]);});const result=await testProvider('zai','zai:glm-4.7-flash',infer,AbortSignal.timeout(1000));expect(result.status).toBe('passed');expect(bodies[0].tool_choice).toBe('auto');expect(bodies[0].tools).toHaveLength(1);expect(bodies[1].tools).toBeUndefined();expect(bodies[1].tool_choice).toBeUndefined();expect(bodies[1].messages.at(-1)).toEqual({role:'tool',tool_call_id:'call',content:'{"result":5}'});});
