import {afterEach,describe,it,expect,vi} from 'vitest';
import {mkdtempSync,readFileSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {CompanyStore} from '../src/storage/store.js';
import {ownerApp,workerApp} from '../src/server/app.js';
import {CorporateBroker} from '../src/tools/broker.js';
import {assertFreeWorkflow} from '../src/tools/github.js';
import type {LocalRuntime} from '../src/runtime/index.js';
import type {Scheduler} from '../src/scheduler/scheduler.js';
import {preferredOwnerPort} from '../src/server/paths.js';
const roots:string[]=[],stores:CompanyStore[]=[];afterEach(()=>{stores.splice(0).forEach(s=>s.close());roots.splice(0).forEach(p=>rmSync(p,{recursive:true,force:true}));});
function setup(){const root=mkdtempSync(join(tmpdir(),'opencorp-api-'));roots.push(root);const store=new CompanyStore(root);stores.push(store);store.bootstrap();const pause=vi.fn(async()=>{}),start=vi.fn();const scheduler={pause,start} as unknown as Scheduler;const runtime={status:()=>({started:false,activeRuns:[],ollama:{running:false},inferenceSlots:1})} as unknown as LocalRuntime;const broker=new CorporateBroker(store,root);const app=ownerApp({store,runtime,broker,scheduler,getUrl:()=> 'http://127.0.0.1:4310'});const token=readFileSync(join(root,'owner-token'),'utf8');const request=(path:string,init:RequestInit={})=>app.request(`http://127.0.0.1:4310${path}`,{...init,headers:{host:'127.0.0.1:4310',authorization:`Bearer ${token}`,...init.headers}});return {store,broker,app,request,pause,start,root};}
describe('Owner and scoped worker boundaries',()=>{
 it('retains an alternate Owner port across daemon restarts',()=>{const root=mkdtempSync(join(tmpdir(),'opencorp-discovery-'));roots.push(root);writeFileSync(join(root,'discovery.json'),JSON.stringify({url:'http://127.0.0.1:48317'}));expect(preferredOwnerPort(root)).toBe(48317);expect(preferredOwnerPort(root,'4312')).toBe(4312);expect(preferredOwnerPort(root,'0')).toBe(0);expect(()=>preferredOwnerPort(root,'70000')).toThrow();writeFileSync(join(root,'discovery.json'),JSON.stringify({url:'https://outside.example:7777'}));expect(preferredOwnerPort(root)).toBe(4310);});
 it('rejects missing credentials, hostile origin/host, worker credentials and unknown controls',async()=>{const {request}=setup();expect((await request('/api/v1/state',{headers:{authorization:''}})).status).toBe(401);expect((await request('/api/v1/state',{headers:{origin:'https://attacker.example'}})).status).toBe(403);expect((await request('/api/v1/state',{headers:{host:'attacker.example'}})).status).toBe(403);expect((await request('/api/v1/events',{headers:{authorization:'Bearer worker-token'}})).status).toBe(401);expect((await request('/api/v1/control',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'destroy'})})).status).toBe(400);});
 it('uses one-time login and stable HttpOnly cookie; persists pause and invokes cancellation',async()=>{const {request,app,store,pause}=setup();const session=await (await request('/api/v1/session',{method:'POST'})).json();const login=await app.request(session.url,{headers:{host:'127.0.0.1:4310'}});const cookie=login.headers.get('set-cookie')!;expect(cookie).toContain('HttpOnly');expect(cookie).toContain('SameSite=Strict');expect((await app.request(session.url,{headers:{host:'127.0.0.1:4310'}})).status).toBe(401);expect((await request('/api/v1/state',{headers:{authorization:'',cookie:cookie.split(';')[0]}})).status).toBe(200);await request('/api/v1/control',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'pause'})});expect(store.company.state).toBe('paused');expect(pause).toHaveBeenCalledWith(false);});
 it('stores Owner chat in same backend and queues an attributed reply',async()=>{const {request,store}=setup();const result=await request('/api/v1/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({content:'Explain current blockers.'})});expect(result.status).toBe(200);expect(store.list('messages')[0].senderId).toBe('owner');const assignment=store.list('assignments')[0];expect(assignment.kind).toBe('conversation');expect(assignment.instructions).toContain('final response');expect(assignment.instructions).toContain('automatically persists');expect(assignment.instructions).toContain('when the request needs them');expect(assignment.acceptance).toEqual(['Answer the actual Owner message; a brief acknowledgment suffices when that is all the Owner requested.']);const spec=await(await request('/api/v1/openapi.json')).json();expect(spec.paths['/api/v1/control']).toBeDefined();});
 it('requires exact session binding and revokes late worker responses after pause',async()=>{const {store,broker}=setup();const ceo=store.list('employees').find(e=>store.level(e.id)==='ceo')!;store.put('models',{id:ceo.modelId,name:ceo.modelId,artifactIdentity:'local-fixture',local:true,available:true,capabilities:['tools']});store.command({kind:'owner'},{type:'control',action:'start'});const assignment=store.command({kind:'owner'},{type:'assignment.create',employeeId:ceo.id,title:'Controlled policy fixture',instructions:'Fixture',acceptance:['Persist'],kind:'management'});const run=store.claimNext({assignmentId:assignment.id})!;const token=broker.mint(run);store.bindSession(run.id,'bound-session');const app=workerApp(broker,()=> '127.0.0.1:4320');const call=(session='bound-session')=>app.request(`http://127.0.0.1:4320/mcp/${run.id}`,{method:'POST',headers:{host:'127.0.0.1:4320',authorization:`Bearer ${token}`,'content-type':'application/json','x-opencorp-session':session},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'company_command',arguments:{command:{type:'product.assess',productId:store.list('products')[0].id,assessment:'Fixture observation',rationale:'Controlled test'}}}})});expect((await call('other')).status).toBe(403);expect((await call()).status).toBe(200);store.command({kind:'owner'},{type:'control',action:'pause'});expect((await call()).status).toBe(403);});
});
describe('$0 workflow publication policy',()=>{it('permits known public standard runners and rejects larger runners, reusable jobs and metered scripts',()=>{const wf=(job:string)=>`name: CI\non: push\njobs:\n  test:\n${job}`;expect(()=>assertFreeWorkflow(wf('    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v6\n      - run: make test'))).not.toThrow();for(const job of ['    runs-on: ubuntu-latest-16-cores\n    steps:\n      - run: make test','    uses: other/repo/.github/workflows/ci.yml@main','    runs-on: macos-15-large\n    steps:\n      - run: make test','    runs-on: ubuntu-latest\n    steps:\n      - run: vercel deploy'])expect(()=>assertFreeWorkflow(wf(job))).toThrow(/charge|runner|workflow|provider/i);});});
