import assert from 'node:assert/strict';
import { createHash,randomUUID } from 'node:crypto';
import { execFile } from 'node:child_process';
import { constants } from 'node:fs';
import { copyFile,lstat,mkdir,mkdtemp,readFile,writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { dirname,join } from 'node:path';
import { parseArgs,promisify } from 'node:util';
import { serve } from '@hono/node-server';
import { OwnerClient } from '../src/cli/client.js';
import { CompanyStore } from '../src/storage/store.js';
import { CorporateBroker } from '../src/tools/broker.js';
import { workerApp } from '../src/server/app.js';
import { LocalRuntime,executeSandboxed,MODEL_ALIASES,type RuntimeEvent } from '../src/runtime/index.js';
import { OwnedOllama } from '../src/runtime/ollama.js';
import { DirectFree } from '../src/runtime/direct-free.js';
import { directFreeConfig } from '../src/server/direct-free-config.js';
import { observeHostMemory } from '../src/runtime/resource-budget.js';
import { managementOutcome } from '../src/scheduler/scheduler.js';
import { setupReasoningManagementFixture } from './qwen-reasoning-management-fixture.js';
import { microWorkplaceEvidence } from './micro-workplace-evidence.js';

const {values}=parseArgs({strict:true,options:{'company-drained':{type:'boolean'},'remote-workers':{type:'string'},help:{type:'boolean'}}});
if(values.help){console.log('verify-mixed-local-gemini.ts --company-drained [--remote-workers 1|4]\nFinite isolated local Qwen48 + Gemini3.5FlashLite qualification using copied real identities, existing weights and parent-only audited credentials. Requires stopped company and idle owned pools. No production company record writes/downloads; shared provider quota reservations are retained.');process.exit(0);}
assert.equal(values['company-drained'],true,'Explicit --company-drained required');
const remoteWorkers=Number(values['remote-workers']??1);assert.ok([1,4].includes(remoteWorkers),'Use one or four remote workers');
const source=join(homedir(),'.local/share/opencorp'),client=new OwnerClient(source),controller=new AbortController(),owner={kind:'owner'} as const;
const root=await mkdtemp(join(homedir(),'.local/share/opencorp-mixed-local-gemini-')),localWorkspace=join(root,'local-workspace'),remoteWorkspace=join(root,'remote-workspace'),staging=join(root,'model-staging');
const store=new CompanyStore(root),broker=new CorporateBroker(store,root),events:RuntimeEvent[]=[],samples:any[]=[],runs:string[]=[];
const report:any={root,passed:false,qualificationOnly:true,productionCompanyWrites:false,sharedProviderRateReservations:true,localModelId:'qwen-main-48k',remoteModelId:'gemini:gemini-3.5-flash-lite',deadlineMs:900000,remoteWorkers,requestedProductiveWorkers:remoteWorkers+1};
let runtime:LocalRuntime|undefined,host='',monitor:ReturnType<typeof setInterval>|undefined,heartbeat:ReturnType<typeof setInterval>|undefined,pendingSample:Promise<void>|undefined;
const server=serve({fetch:workerApp(broker,()=>host).fetch,hostname:'127.0.0.1',port:0});
const abort=()=>controller.abort(new Error('Mixed qualification interrupted'));process.on('SIGINT',abort);process.on('SIGTERM',abort);
const timer=setTimeout(()=>controller.abort(new Error('Mixed qualification reached15minute limit')),900000),systemRead=promisify(execFile),hash=(v:Buffer|string)=>createHash('sha256').update(v).digest('hex');
function idle(s:any){assert.ok(['paused','stopped'].includes(s.company.state),'Production company must already be stopped');assert.ok(!s.runs.some((r:any)=>['running','cancelling','queued','uncertain'].includes(r.status)),'Production runs are not drained');assert.equal(s.resources.runtime.ollama.running,false);assert.equal(s.resources.runtime.microOllama.running,false);assert.equal(s.resources.runtime.activeRuns.length,0);}
async function sample(){const at=Date.now(),memory=observeHostMemory(),ownerBegan=Date.now(),s=await client.state(AbortSignal.timeout(5000));const ownerResponseMs=Date.now()-ownerBegan;idle(s);const swap=await systemRead('/usr/sbin/sysctl',['-n','vm.swapusage'],{timeout:2000});samples.push({at,ownerResponseMs,memory,swap:swap.stdout.trim(),runtime:runtime?.status()});assert.equal(memory.pressure,'normal');assert.ok((memory.available??memory.free)>=2*1024**3,'Host memory reserve below2GiB');}
async function stage(){const [name,version]=MODEL_ALIASES['qwen-main'].split(':'),relative=join('manifests/registry.ollama.ai/library',name,version),from=join(source,'runtime/ollama/models'),raw=await readFile(join(from,relative)),manifest=JSON.parse(raw.toString());await mkdir(join(staging,'blobs'),{recursive:true});for(const blob of [...manifest.layers,manifest.config]){assert.match(blob.digest,/^sha256:[a-f0-9]{64}$/);const file=blob.digest.replace(':','-');assert.equal((await lstat(join(from,'blobs',file))).size,blob.size);await copyFile(join(from,'blobs',file),join(staging,'blobs',file),constants.COPYFILE_FICLONE);}await mkdir(dirname(join(staging,relative)),{recursive:true});await writeFile(join(staging,relative),raw);report.sourceManifestHash=hash(raw);}
try{
 await new Promise<void>(resolve=>server.once('listening',resolve));const address=server.address();assert.ok(address&&typeof address!=='string');host=`127.0.0.1:${address.port}`;
 report.stage='source-drain';const snapshot=await client.state();idle(snapshot);await sample();
 const ceo=snapshot.employees.find((e:any)=>e.status==='active'&&snapshot.positions.find((p:any)=>p.id===e.positionId)?.level==='ceo'),employee=snapshot.employees.find((e:any)=>e.status==='active'&&e.id!==ceo?.id&&e.homeManagerId===ceo?.id);assert.ok(ceo&&employee,'Two actual active employee identities required');
 const remoteEmployees=[ceo,...snapshot.employees.filter((e:any)=>e.status==='active'&&e.id!==ceo.id&&e.id!==employee.id&&['executive','ceo'].includes(snapshot.positions.find((p:any)=>p.id===e.positionId)?.level??''))].slice(0,remoteWorkers);assert.equal(remoteEmployees.length,remoteWorkers,'Distinct real managers required');
 store.put('company',{...snapshot.company,id:randomUUID(),state:'stopped',mandate:'Isolated synthetic qualification only; not production company work.',qualification:true});store.put('policy',{...snapshot.policy,id:randomUUID(),companyId:store.company.id,allowedRepositories:[],maxInference:remoteWorkers+1,maxProductiveTurns:remoteWorkers+1,qualification:true});
 for(const table of ['departments','positions','employees','appointments'] as const)for(const record of snapshot[table])store.put(table,{...record,qualificationCopy:true});
 report.identities=[employee,...remoteEmployees].map(e=>({id:e.id,name:e.name,positionId:e.positionId,formedAt:e.createdAt}));await Promise.all([mkdir(localWorkspace),mkdir(remoteWorkspace),stage()]);
 report.stage='model-identity';const direct=directFreeConfig(source,[report.remoteModelId]);assert.ok(direct?.gemini);const remote=(await new DirectFree('gemini',direct.gemini).models(controller.signal))[0]!;
 const pool=new OwnedOllama({dataRoot:root,modelStore:staging});let local;await sample();controller.signal.throwIfAborted();try{await pool.start();local=(await pool.models(49152)).find(m=>m.id==='qwen-main-48k');}finally{await pool.stop();}assert.ok(local&&local.contextTokens===49152);
 const profile={modelId:remote.id,artifactIdentity:remote.artifactIdentity,maxConcurrentTurns:remoteWorkers},providerCap={provider:'gemini' as const,maxConcurrentTurns:remoteWorkers};
 const options={dataRoot:root,modelStore:staging,directFree:direct,resourceBudget:{maxConcurrentTurns:remoteWorkers+1,maxProductiveTurns:remoteWorkers+1,productiveArtifactIdentity:local.artifactIdentity,...(remoteWorkers===1?{productiveRemoteModelId:remote.id,productiveRemoteArtifactIdentity:remote.artifactIdentity}:{productiveRemoteProfiles:[profile],productiveProviderCaps:[providerCap]}),maxSocialTurns:1,maxLoadedModels:1}};
 runtime=new LocalRuntime({...options,onEvent:event=>{if(event.type.startsWith('runtime.inference.')||event.type==='runtime.resource.refused')events.push(event);if(['runtime.inference.failed','runtime.resource.refused'].includes(event.type))controller.abort(new Error('Mixed qualification provider/resource failure'));}});
 // Private trial admission is configuration under test, not a production qualification receipt.
 store.update('policy',store.policy.id,{concurrencyQualification:{passed:true,stableMaxInference:remoteWorkers+1,largePlusSmall:true,evidence:'Isolated experiment setup only'},productiveConcurrencyQualification:remoteWorkers===1?{passed:true,mode:'local-remote',artifactIdentity:local.artifactIdentity,remoteModelId:remote.id,remoteArtifactIdentity:remote.artifactIdentity,evidence:'Isolated experiment setup only'}:{passed:true,mode:'local-remotes',stableMaxProductiveTurns:remoteWorkers+1,artifactIdentity:local.artifactIdentity,remoteProfiles:[profile],providerCaps:[providerCap],evidence:'Isolated experiment setup only'}});
 report.stage='isolated-setup';const fixtures=remoteEmployees.map((manager,index)=>{const workspace=join(remoteWorkspace,String(index));return {manager,workspace};});for(const item of fixtures)await mkdir(item.workspace);
 const remoteFixtures=fixtures.map(item=>({...setupReasoningManagementFixture(store,[local,remote],remote,item.workspace,employee.id,item.manager.id),workspace:item.workspace}));runs.push(...remoteFixtures.map(item=>item.run.id));for(const fixture of remoteFixtures){const actor={kind:'employee' as const,employeeId:fixture.ceo.id,runId:fixture.run.id,policyRevision:fixture.run.policyRevision};store.validateActor(actor);assert.ok(broker.toolsFor(actor).some(tool=>tool.name==='revise_and_retry_assignment'),'Every remote worker needs current recovery tool access before inference');}store.update('employees',employee.id,{modelId:local.id});
 const task=store.command(owner,{type:'assignment.create',employeeId:employee.id,supervisorId:ceo.id,kind:'management',title:'Synthetic department utility',instructions:'Create department-summary.mjs reading departments.json and output JSON {departments,employees}, counting departments and summing employee counts.',acceptance:['Actual utility passes three independent input cases.']});
 const localRun=store.claimNext({assignmentId:task.id,workspace:localWorkspace});assert.ok(localRun);runs.push(localRun.id);await writeFile(join(localWorkspace,'departments.json'),JSON.stringify([{name:'Research',employees:3},{name:'Operations',employees:4}]));
 report.models={local,remote};heartbeat=setInterval(()=>runs.forEach(id=>store.heartbeat(id)),30000);monitor=setInterval(()=>{if(pendingSample)return;pendingSample=sample().catch(e=>controller.abort(e)).finally(()=>{pendingSample=undefined;});},1000);
 const execute=runtime.execute.bind(runtime),common={signal:controller.signal,timeoutMs:900000,workload:'productive' as const};
 report.stage='paired-inference';const localPromise=execute({...common,runId:localRun.id,employeeId:employee.id,modelId:local.id,workspace:localWorkspace,contextTokens:49152,system:'Work only in this isolated fixture workspace. Create the requested useful utility using native file tools. This is not production delivery.',prompt:task.instructions,onSession:id=>{store.bindSession(localRun.id,id,localWorkspace);}});
 // Wait for actual local public generation before starting the fast remote task.
 while(!events.some(e=>e.runId===localRun.id&&e.type==='runtime.inference.first_content')){controller.signal.throwIfAborted();await Promise.race([localPromise.then(()=>{throw new Error('Local finished before remote launch');}),new Promise(resolve=>setTimeout(resolve,100))]);}
 const remotePromises=remoteFixtures.map(fixture=>execute({...common,runId:fixture.run.id,employeeId:fixture.ceo.id,modelId:remote.id,directFreeModels:[remote.id],workspace:fixture.workspace,contextTokens:32768,corporateOnly:true,brokerUrl:`http://${host}/mcp/${fixture.run.id}`,token:broker.mint(fixture.run),onSession:id=>{store.bindSession(fixture.run.id,id,fixture.workspace);},system:`Synthetic management qualification. Use the exact advertised corporate_ tool names and JSON schemas. Begin with corporate_company_help for the trusted diagnosis guidance, then read the exact original and failed run. Preserve acceptance; use corporate_revise_and_retry_assignment with your own corrected instructions and rationale when justified. End after the actual correction and retry receipt.`,prompt:`Inspect original assignment ${fixture.original.id}, failed run ${fixture.failed.id}, and target department ${fixture.department.id}. Correct the omitted department with your own instructions/rationale and retry the original if justified. Never execute/complete the subordinate task or change acceptance.`}));
 const outcomes=await Promise.allSettled([localPromise,...remotePromises]);for(const outcome of outcomes)assert.equal(outcome.status,'fulfilled',outcome.status==='rejected'?String(outcome.reason):'');controller.signal.throwIfAborted();
 const results=outcomes.map(o=>(o as PromiseFulfilledResult<any>).value);report.results=results.map(result=>({artifactIdentity:result.artifactIdentity,usage:result.usage,completion:result.completion,messagesPath:result.messagesPath,diagnosticsPath:result.diagnosticsPath}));for(const result of results)assert.ok(result.usage.requests>0&&result.text.trim()&&!result.completion.exhausted,'Actual unexhausted terminal outputs required');for(const [i,model]of [local,...remoteFixtures.map(()=>remote)].entries()){assert.equal(results[i].artifactIdentity,model.artifactIdentity);const binding=JSON.parse(await readFile(join(root,'runtime/employees',i===0?localRun.id:remoteFixtures[i-1]!.run.id,'binding.json'),'utf8'));assert.equal(binding.model.id,model.id);assert.equal(binding.model.artifactIdentity,model.artifactIdentity);assert.equal(binding.model.contextTokens,i===0?49152:32768);}
 report.stage='utility-verification';const checks=[];for(const data of [[{employees:3},{employees:4}],[{employees:11},{employees:7}],[]]){await writeFile(join(localWorkspace,'departments.json'),JSON.stringify(data));const checked=await executeSandboxed({dataRoot:root,workspace:localWorkspace,command:[process.execPath,'department-summary.mjs'],timeoutMs:10000,signal:controller.signal});assert.equal(checked.code,0);assert.deepEqual(JSON.parse(checked.stdout),{departments:data.length,employees:data.reduce((n,d)=>n+d.employees,0)});checks.push({data,checked});}
 report.stage='management-verification';const management=remoteFixtures.map(fixture=>{const retained=store.need('assignments',fixture.original.id),outcome=managementOutcome(store,store.need('assignments',fixture.task.id),store.need('runs',fixture.run.id));assert.ok(outcome.passed);assert.equal(retained.status,'queued');assert.deepEqual(retained.acceptance,fixture.original.acceptance);assert.notEqual(retained.instructions,fixture.original.instructions);assert.equal(retained.faultCorrections.at(-1).runId,fixture.run.id);assert.equal(retained.retryDecisions.at(-1).runId,fixture.run.id);return {fixture,retained,outcome};});
 report.stage='overlap-and-host-verification';await pendingSample;await sample();controller.signal.throwIfAborted();const overlap=microWorkplaceEvidence(events,true);assert.ok(overlap.interleavedPairs.length,'No observed interleaved public generation');assert.ok(overlap.peakDispatchedRequests>=remoteWorkers+1,'No overlapping runtime request intervals for all workers (these intervals include provider pacing)');const publicParticipants=new Set(overlap.interleavedPairs.flatMap(pair=>[pair.firstRunId,pair.secondRunId]));for(const id of runs)assert.ok(publicParticipants.has(id),'Each worker must participate in observed public stream interleaving');assert.equal(runtime.status().ollama.concurrentInference,1);
 for(const [i,item]of management.entries())store.finishRun(item.fixture.run.id,{status:'succeeded',managementResult:item.outcome,modelIdentity:results[i+1].artifactIdentity,usage:results[i+1].usage});store.finishRun(localRun.id,{status:'succeeded',managementResult:{passed:true,summary:'Isolated utility passed three sandboxed input cases.'},modelIdentity:results[0].artifactIdentity,usage:results[0].usage});
 report.stage='passed';report.passed=true;report.results=results.map(result=>({artifactIdentity:result.artifactIdentity,usage:result.usage,completion:result.completion,messagesPath:result.messagesPath,diagnosticsPath:result.diagnosticsPath}));report.checks=checks;report.management=management.map(item=>({employeeId:item.fixture.ceo.id,assignmentId:item.fixture.task.id,outcome:item.outcome,correction:item.retained.faultCorrections,retry:item.retained.retryDecisions}));report.overlap=overlap;
}catch(error){controller.abort(error);report.error='Mixed qualification failed; inspect retained stage and bounded operational evidence.';report.failureType=error instanceof assert.AssertionError?'assertion':'runtime-or-control';process.exitCode=1;for(const id of runs)if(store.get('runs',id)?.status==='running')store.finishRun(id,{status:'failed',error:report.error});}
finally{clearTimeout(timer);if(monitor)clearInterval(monitor);if(heartbeat)clearInterval(heartbeat);await pendingSample;if(controller.signal.aborted){report.passed=false;process.exitCode=1;}controller.abort();try{await runtime?.stop();await broker.cancel();report.ownedRuntimeStopped=true;}catch{report.passed=false;report.stopError='Owned runtime shutdown did not confirm completion';process.exitCode=1;}await new Promise<void>(resolve=>server.close(()=>resolve()));report.events=events;report.samples=samples;await writeFile(join(root,'qualification.json'),JSON.stringify(report,null,2),{mode:0o600});store.close();process.off('SIGINT',abort);process.off('SIGTERM',abort);console.log(JSON.stringify({root,passed:report.passed,error:report.error}));}
