import { RunsView } from './runs.js';
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import type { Artifact, CompanySnapshot, Decision, DeliveryReceipt, ExternalAction, Knowledge, Project, RecordBase } from '../core/types.js';
import { employeeDisplayName } from '../core/narratives.js';
import { deliveriesFor, deliveryFor } from '../core/delivery.js';
import { request, WebApiError } from './api.js';
import { Narratives } from './narratives.js';
import { ArtifactLink, artifactContentHref } from './artifacts.js';
import './style.css';
import { Hierarchy, RecruitmentView, WorkplaceView, ResponsibilitiesView, employeeActivity } from './expansion.js';
import { ProvidersView } from './providers.js';

type Route = { page: string; id?: string };
const pages = ['Overview', 'Runs', 'Products', 'Projects', 'Organization', 'Recruitment', 'Workplace', 'Responsibilities', 'Conversations', 'Knowledge', 'Attention', 'Providers', 'Settings'];
const parseRoute = (): Route => { const [page, id] = window.location.hash.slice(1).split('/'); return { page: page || 'overview', id }; };
const readable = (text: string | undefined | null) => (text || 'Not recorded').replaceAll('_', ' ');
const date = (value: string | undefined) => value ? new Date(value).toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }) : 'Not recorded';
const shortId = (value: string) => value.slice(0, 8);
const remoteLink = (value: string | undefined) => { try { const url = new URL(value || ''); return ['http:', 'https:'].includes(url.protocol) ? url.href : undefined; } catch { return undefined; } };
const contentText = (value: unknown): string => typeof value === 'string' ? value : JSON.stringify(value, null, 2);
function Badge({ value }: { value: string }) { return <span className={`badge status-${value.replaceAll('_', '-')}`}>{readable(value)}</span>; }
function Empty({ children }: { children: React.ReactNode }) { return <div className="empty">{children}</div>; }
function Metadata({ children }: { children: React.ReactNode }) { return <dl className="metadata">{children}</dl>; }
function Field({ title, children }: { title: string; children: React.ReactNode }) { return <div><dt>{title}</dt><dd>{children || 'Not recorded'}</dd></div>; }
function Section({ title, note, children, action }: { title: string; note?: string; children: React.ReactNode; action?: React.ReactNode }) { return <section className="section"><div className="section-heading"><div><h2>{title}</h2>{note && <p className="muted">{note}</p>}</div>{action}</div>{children}</section>; }
function Details({ value, label = 'Record details' }: { value: unknown; label?: string }) { return <details className="record-details"><summary>{label}</summary><pre>{JSON.stringify(value, null, 2)}</pre></details>; }
function Name({ id, state }: { id: string | null | undefined; state: CompanySnapshot }) {
  if (!id || id === 'owner') return <span>{id === 'owner' ? 'You · Owner' : 'Unassigned'}</span>;
  const employee = state.employees.find((item) => item.id === id);
  return employee ? <a href={`#employees/${id}`}>{employeeDisplayName(employee, state.employees)}</a> : <span>{shortId(id)}</span>;
}
function Records({ items, empty, render }: { items: Array<RecordBase>; empty: string; render: (item: RecordBase) => React.ReactNode }) { return items.length ? <div className="records">{items.map((item) => <div key={item.id} className="record">{render(item)}</div>)}</div> : <Empty>{empty}</Empty>; }

function App() {
  const [state, setState] = useState<CompanySnapshot>();
  const [route, setRoute] = useState(parseRoute);
  const [error, setError] = useState(''); const [auth, setAuth] = useState(false);
  const [connected, setConnected] = useState(false); const [updated, setUpdated] = useState('');
  const [notice, setNotice] = useState(''); const [pending, setPending] = useState(false);
  const [confirmStop, setConfirmStop] = useState(false);
  const fetching = useRef(false);
  const refresh = useCallback(async () => {
    if (fetching.current) return;
    fetching.current = true;
    try { setState(await request<CompanySnapshot>('state', undefined, AbortSignal.timeout(10_000))); setUpdated(new Date().toISOString()); setError(''); setAuth(false); setConnected(true); }
    catch (failure) { setError(failure instanceof Error ? failure.message : 'Connection failed'); setAuth(failure instanceof WebApiError && failure.status === 401); setConnected(false); }
    finally { fetching.current = false; }
  }, []);
  useEffect(() => { const change = () => setRoute(parseRoute()); window.addEventListener('hashchange', change); return () => window.removeEventListener('hashchange', change); }, []);
  useEffect(() => {
    void refresh(); const stream = new EventSource('/api/v1/events');
    stream.onmessage = () => { void refresh(); }; stream.addEventListener('change', () => { void refresh(); }); stream.addEventListener('company', () => { void refresh(); });
    stream.onopen = () => { setConnected(true); void refresh(); }; stream.onerror = () => setConnected(false);
    const timer = window.setInterval(() => { void refresh(); }, 5000);
    return () => { stream.close(); window.clearInterval(timer); };
  }, [refresh]);
  const mutate = async (path: string, body: unknown, success: string) => {
    setPending(true); setNotice('');
    try { const result = await request<unknown>(path, body); await refresh(); setNotice(success); return result; }
    catch (failure) { const message = failure instanceof Error ? failure.message : 'Action failed'; setNotice(message); throw failure; }
    finally { setPending(false); }
  };
  const control = async (action: string) => { setConfirmStop(false); try { await mutate('control', { action }, ({ pause: 'Company paused. Work is preserved.', resume: 'Company resumed.', stop: 'Company stopped. This state survives restart.', start: 'Company started.' } as Record<string, string>)[action]); } catch { /* notice holds error */ } };
  const activeAttention = state?.attention.filter((item) => item.status === 'open') || [];
  const title = route.page === 'employees' ? state?.employees.find((item) => item.id === route.id)?.name || 'Employee' : pages.find((page) => page.toLowerCase() === route.page) || 'Overview';
  return <div className="workspace">
    <a className="skip-link" href="#main-content" onClick={(event) => { event.preventDefault(); document.getElementById('main-content')?.focus(); }}>Skip to content</a>
    <aside className="sidebar"><a className="brand" href="#overview" aria-label="OpenCorp overview"><span className="brand-mark">OC</span><span>OpenCorp<small>Owner workspace</small></span></a>
      <nav aria-label="Main navigation">{pages.map((page) => <a key={page} href={`#${page.toLowerCase()}`} aria-current={route.page === page.toLowerCase() || (page === 'Organization' && route.page === 'employees') ? 'page' : undefined}><span>{page}</span>{page === 'Attention' && activeAttention.length > 0 && <span className="nav-count">{activeAttention.length}</span>}</a>)}</nav>
      <div className="sidebar-footer"><div className="local-label"><span className={connected ? 'signal' : 'signal offline'}></span>{connected ? 'Local service connected' : 'Reconnecting to service'}</div><p>{state?.policy.directFreeModels?.length ? 'Local + free remote inference' : state?.policy.openRouterFreeModels?.length ? 'Local + free OpenRouter inference' : 'Local inference'}<br/>$0 unapproved spending</p><small>Closing this window leaves the service running.</small></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb">Company <span>/</span> {title}</div><div className="topbar-state">{state && <Badge value={state.company.state}/>}<span className="owner-label">Owner</span></div></header>
      <main id="main-content" tabIndex={-1}><div className="page-heading"><div><p className="eyebrow">{route.page === 'overview' ? 'Company desk' : 'OpenCorp'}</p><h1>{title}</h1></div><div className="page-tools"><button className="quiet" onClick={() => { void refresh(); }}>Refresh</button>{route.page === 'overview' && state && <><button disabled={pending} onClick={() => { void control(state.company.state === 'running' ? 'pause' : state.company.state === 'paused' ? 'resume' : 'start'); }}>{state.company.state === 'running' ? 'Pause company' : state.company.state === 'paused' ? 'Resume company' : 'Start company'}</button><button className="quiet danger" disabled={pending || state.company.state === 'stopped'} onClick={() => setConfirmStop(true)}>Stop</button></>}</div></div>
      {error && <div className="banner error" role="alert"><strong>{auth ? 'Open this workspace through OpenCorp' : 'Service unavailable'}</strong><p>{auth ? 'Run opencorp open to establish your Owner session.' : `${error}. Showing the last received state. Retrying automatically.`}</p><button onClick={() => { void refresh(); }}>Retry connection</button></div>}
      {notice && <div className="banner notice" role="status">{notice}<button className="quiet" aria-label="Dismiss notification" onClick={() => setNotice('')}>Dismiss</button></div>}
      {confirmStop && <div className="banner" role="alert"><strong>Stop company work?</strong><p>Active model turns will be cancelled. Work is preserved. OpenCorp stays stopped after service restart until you start it.</p><div className="button-row"><button className="danger-button" onClick={() => { void control('stop'); }}>Stop company</button><button className="quiet" onClick={() => setConfirmStop(false)}>Keep current state</button></div></div>}
      {!state ? <Empty>{error ? 'Waiting for the local service.' : 'Loading your company…'}</Empty> : <>
        {route.page === 'overview' && <Overview state={state}/>}
        {route.page === 'runs' && <RunsView state={state} id={route.id}/>}
        {route.page === 'products' && <Products state={state} selected={route.id}/>}
        {route.page === 'projects' && <Projects state={state} selected={route.id}/>}
        {route.page === 'organization' && <Organization state={state}/>}
        {route.page === 'recruitment' && <RecruitmentView state={state}/>}
        {route.page === 'workplace' && <WorkplaceView state={state} mutate={mutate} pending={pending}/>}
        {route.page === 'responsibilities' && <ResponsibilitiesView state={state}/>}
        {route.page === 'employees' && <EmployeeView state={state} id={route.id}/>}
        {route.page === 'conversations' && <Conversations state={state} mutate={mutate} pending={pending}/>}
        {route.page === 'knowledge' && <KnowledgeView state={state} selected={route.id}/>}
        {route.page === 'attention' && <AttentionView state={state} mutate={mutate} pending={pending}/>}
        {route.page === 'providers' && <ProvidersView/>}
        {route.page === 'settings' && <Settings state={state} mutate={mutate} pending={pending} control={control}/>}
      </>}
      {updated && <footer className="page-footer">State received {date(updated)} · {connected ? 'Connected' : 'Reconnecting'} · One persistent company</footer>}
      </main>
    </div>
  </div>;
}
function Overview({ state }: { state: CompanySnapshot }) {
  const active = state.assignments.filter((item) => ['running', 'queued', 'awaiting_review', 'needs_changes', 'blocked'].includes(item.status));
  const delivered = state.projects.flatMap(project => deliveriesFor(project).filter(delivery => delivery.state === 'merged').map(delivery => ({ project, delivery })));
  const priorities = [...state.products].sort((a, b) => b.priority - a.priority);
  return <>
    <div className="mandate"><div><p className="eyebrow">Standing mandate</p><p>{state.company.mandate}</p></div><a href="#conversations">Speak with the CEO <span aria-hidden="true">↗</span></a></div>
    <div className="metrics"><div><span>Current assignments</span><strong>{active.length}</strong><small>{active.filter((item) => item.status === 'running').length} running · {active.filter((item) => item.status === 'queued').length} queued</small></div><div><span>Product deliveries</span><strong>{delivered.length}</strong><small>Confirmed GitHub merges</small></div><div><span>Owner attention</span><strong>{state.attention.filter((item) => item.status === 'open').length}</strong><a href="#attention">View exact prerequisites →</a></div><div><span>Inference capacity</span><strong>{state.runs.filter((item) => item.status === 'running').length}<em> / {state.policy.maxInference}</em></strong><small>Active runs / allowed slots</small></div></div>
    <Section title="Portfolio priorities" note="Leadership’s current direction and reasons." action={<a href="#products">All products →</a>}><div className="product-grid">{priorities.map((product) => <article key={product.id} className="product-card"><div className="card-heading"><a href={`#products/${product.id}`}><h3>{product.name}</h3></a><Badge value={product.status}/></div><p>{product.rationale || 'Leadership has not recorded a priority rationale yet.'}</p><p className="muted">{product.assessment || 'Portfolio assessment is pending.'}</p><div className="card-footer"><span>{state.projects.filter((item) => item.productId === product.id && !['completed', 'cancelled'].includes(item.status)).length} open projects</span><a href={`#products/${product.id}`}>View product ↗</a></div></article>)}</div></Section>
    <div className="two-column"><Section title="Current work"><AssignmentTable state={state} assignments={active}/></Section><Section title="Product deliveries">{delivered.length ? <div className="records">{delivered.slice(-6).reverse().map(({ project, delivery }) => <article className="record" key={delivery.artifactId}><a href={`#projects/${project.id}`}><h3>{project.name}</h3></a><p><Name id={project.supervisorId} state={state}/> · {date(delivery.deliveredAt)}</p>{remoteLink(delivery.prUrl) && <a href={remoteLink(delivery.prUrl)} target="_blank" rel="noreferrer">Open merged pull request ↗</a>}{state.artifacts.filter((artifact) => artifact.id === delivery.artifactId).map((artifact) => <ArtifactLink key={artifact.id} artifact={artifact} importer={<Name id={artifact.employeeId} state={state}/>}/>)}</article>)}</div> : <Empty>Reviewed product changes appear here after their merge is confirmed.</Empty>}</Section></div>
    <Section title="Recent company activity"><div className="activity-list">{state.events.slice(-8).reverse().map((event) => <div key={event.id}><time>{date(event.createdAt)}</time><div><strong>{readable(event.type.replaceAll('.', ' · '))}</strong><Details value={event.payload} label="Activity details"/></div></div>)}{!state.events.length && <Empty>No company events yet.</Empty>}</div></Section>
  </>;
}
function AssignmentTable({ state, assignments }: { state: CompanySnapshot; assignments: CompanySnapshot['assignments'] }) {
  return assignments.length ? <div className="table-scroll"><table><thead><tr><th>Assignment</th><th>Employee</th><th>State</th></tr></thead><tbody>{assignments.map((assignment) => <tr key={assignment.id}><td><a href={assignment.projectId ? `#projects/${assignment.projectId}` : `#employees/${assignment.employeeId}`}>{assignment.title}</a>{assignment.dependencies.length > 0 && <small>{assignment.dependencies.length} dependencies</small>}</td><td><Name id={assignment.employeeId} state={state}/></td><td><Badge value={assignment.status}/></td></tr>)}</tbody></table></div> : <Empty>No assignments in this view. Leadership selects and staffs work when the company runs.</Empty>;
}
function Artifacts({ state, artifacts }: { state: CompanySnapshot; artifacts: Artifact[] }) {
  return artifacts.length ? <div className="records">{artifacts.map((artifact) => <article className="record" key={artifact.id}><ArtifactLink artifact={artifact} importer={<Name id={artifact.employeeId} state={state}/>}/><p className="muted">{!Object.hasOwn(artifact, 'sourcePullRequest') && !Object.hasOwn(artifact, 'reviewWorkspace') && <>By <Name id={artifact.employeeId} state={state}/> · </>}{date(artifact.createdAt)}</p>{state.reviews.filter((review) => review.artifactId === artifact.id).map((review) => <div className="review" key={review.id}><Badge value={review.verdict}/><p>{review.rationale}</p><p className="muted">Reviewed by <Name id={review.employeeId} state={state}/> · <code>{review.artifactIdentity}</code></p><Details value={review.checks} label="Review checks"/></div>)}<Details value={artifact.checks} label="Artifact checks"/></article>)}</div> : <Empty>No artifacts have been recorded yet.</Empty>;
}
function Actions({ actions }: { actions: ExternalAction[] }) {
  return actions.length ? <div className="records">{actions.map((action) => <article className="record" key={action.id}><div className="card-heading"><h3>{readable(action.kind)}</h3><Badge value={action.status}/></div><p>{remoteLink(action.remoteRef) ? <a href={remoteLink(action.remoteRef)} target="_blank" rel="noreferrer">Open actual result ↗</a> : 'No confirmed remote result'}</p><p className="muted">Destination: {action.target}</p><Details value={action.content} label="Intended content"/><Details value={{ cost: action.cost, costEvidence: action.costEvidence, result: action.result, remoteRef: action.remoteRef }} label="Delivery and cost details"/></article>)}</div> : <Empty>No external actions recorded.</Empty>;
}
function Products({ state, selected }: { state: CompanySnapshot; selected?: string }) {
  const products = selected ? state.products.filter((item) => item.id === selected) : state.products;
  if (!products.length) return <Empty>Product not found. <a href="#products">View all products</a></Empty>;
  return <>{selected && <a className="back-link" href="#products">← All products</a>}{products.map((product) => <Section key={product.id} title={product.name} action={<Badge value={product.status}/>}>
    <p className="lead-text">{product.assessment || 'Leadership has not yet recorded an assessment.'}</p><Metadata><Field title="Priority rationale">{product.rationale}</Field><Field title="Repository"><code>{product.repository}</code></Field></Metadata>
    <div className="two-column"><div><h3>Goals</h3><Narratives values={product.goals} empty="Goals will appear after leadership assesses this product."/></div><div><h3>Roadmap</h3><Narratives values={product.roadmap} empty="No roadmap recorded yet."/></div></div>
    <h3 className="subheading">Projects</h3><ProjectCards state={state} projects={state.projects.filter((item) => item.productId === product.id)}/>
    <h3 className="subheading">Releases & communications</h3><Actions actions={state.actions.filter((item) => item.productId === product.id)}/>
  </Section>)}</>;
}
function ProjectCards({ state, projects }: { state: CompanySnapshot; projects: Project[] }) { return projects.length ? <div className="project-list">{projects.map((project) => <a className="project-row" key={project.id} href={`#projects/${project.id}`}><div><h3>{project.name}</h3><p>{project.outcome}</p><small>{state.products.find((item) => item.id === project.productId)?.name || 'Company'} · {state.assignments.filter((item) => item.projectId === project.id).length} assignments</small></div><Badge value={project.status}/><span aria-hidden="true">↗</span></a>)}</div> : <Empty>No projects yet. Leadership creates finite projects from its product goals.</Empty>; }
function AssignmentDetails({ state, assignment }: { state: CompanySnapshot; assignment: CompanySnapshot['assignments'][number] }) {
  const runs = state.runs.filter((item) => item.assignmentId === assignment.id);
  return <details className="assignment-detail"><summary>{assignment.title} · {readable(assignment.status)}</summary><h4>Instructions</h4><p className="preserve-lines">{assignment.instructions}</p><h4>Acceptance</h4><Narratives values={assignment.acceptance} empty="None recorded"/><p>Supervisor: <Name id={assignment.supervisorId} state={state}/></p><p>Dependencies: {assignment.dependencies.length ? assignment.dependencies.map((id) => state.assignments.find((item) => item.id === id)?.title || id).join('; ') : 'None'}</p>{assignment.blockedReason && <p className="preserve-lines"><strong>Recorded blocker:</strong> {assignment.blockedReason}</p>}{runs.length ? <Details value={runs} label={`Employee runs (${runs.length})`}/> : <p className="muted">No employee run has been recorded for this assignment.</p>}</details>;
}
function DeliveryRecord({ state, project, delivery }: { state: CompanySnapshot; project: Project; delivery: DeliveryReceipt }) {
  const latest = delivery.artifactId === project.delivery?.artifactId;
  const prUrl = remoteLink(delivery.prUrl);
  const artifact = state.artifacts.find((item) => item.id === delivery.artifactId);
  const blocked = state.assignments.filter((item) => item.projectId === project.id && item.payload?.artifactId === delivery.artifactId && item.status === 'blocked' && item.blockedReason).at(-1);
  const pollError = [...state.events].reverse().find((event) => event.type === 'delivery.poll_error' && event.payload?.projectId === project.id && (event.payload.artifactId === delivery.artifactId || !event.payload.artifactId && deliveriesFor(project).length === 1));
  return <article className="record" data-delivery-artifact={delivery.artifactId}>
    <div className="card-heading"><h3>{latest ? 'Latest delivery' : 'Earlier delivery'}{delivery.prNumber ? ` · PR #${delivery.prNumber}` : ''}</h3><Badge value={delivery.state}/></div>
    {delivery.state === 'awaiting_checks' && <p>Required GitHub checks and the exact reviewed-head merge must be confirmed before delivery is complete.</p>}
    <Metadata><Field title="Pull request">{prUrl ? <a href={prUrl} target="_blank" rel="noreferrer">{delivery.prNumber ? `Pull request #${delivery.prNumber}` : 'Open pull request'} ↗</a> : 'No pull request URL recorded'}</Field><Field title="Reviewed source commit"><code>{delivery.identity || 'Not recorded'}</code></Field><Field title="Merge commit"><code>{delivery.mergeCommit || 'Not recorded'}</code></Field><Field title="Observed default-branch head"><code>{delivery.defaultBranchHead || 'Not recorded'}</code></Field><Field title="Delivery recorded">{delivery.deliveredAt ? date(delivery.deliveredAt) : 'Not recorded'}</Field></Metadata>
    {delivery.remainingGate && <p className="preserve-lines"><strong>Remaining delivery requirement:</strong> {delivery.remainingGate}</p>}
    {delivery.state !== 'merged' && blocked && <p className="preserve-lines"><strong>Recorded delivery blocker:</strong> {blocked.blockedReason}</p>}
    {latest && delivery.state === 'awaiting_checks' && pollError && <p className="preserve-lines"><strong>Latest recorded check error ({date(pollError.createdAt)}):</strong> {contentText(pollError.payload.error)}</p>}
    {artifact && <ArtifactLink artifact={artifact} importer={<Name id={artifact.employeeId} state={state}/>}/>}<Details value={delivery} label="Delivery receipt"/>
  </article>;
}
function ProjectDelivery({ state, project }: { state: CompanySnapshot; project: Project }) {
  const deliveries = deliveriesFor(project);
  return <Section title="Product deliveries" note="Each receipt belongs to one reviewed artifact. Project completion is recorded against its acceptance conditions.">{deliveries.length ? <div className="records">{deliveries.slice().reverse().map(delivery => <DeliveryRecord key={delivery.artifactId} state={state} project={project} delivery={delivery}/>)}</div> : <Empty>No product delivery has been recorded for this project.</Empty>}</Section>;
}
type CriterionEvidence = { criterion: string; rationale: string; sources: Array<{ type: 'artifact' | 'delivery' | 'release'; id: string; reviewId: string; identity: string }> };
function ProjectAcceptance({ state, project }: { state: CompanySnapshot; project: Project }) {
  const evidence: CriterionEvidence[] = project.completionEvidence || [];
  const completed = project.acceptance.filter(criterion => evidence.some(item => item.criterion === criterion)).length;
  if (!project.acceptance.length) return <Empty>No acceptance conditions recorded.</Empty>;
  return <><p className="muted">{completed} of {project.acceptance.length} criteria have recorded completion evidence · {project.acceptance.length - completed} remaining</p><div className="records">{project.acceptance.map((criterion, index) => {
    const entry = evidence.find(item => item.criterion === criterion);
    return <article className="record" key={index} data-acceptance-index={index}><div className="card-heading"><h4>{criterion}</h4>{entry ? <Badge value="completed"/> : <span className="badge status-queued">Remaining</span>}</div>{entry ? <><p>{entry.rationale}</p>{entry.sources.map((source, sourceIndex) => {
      const artifact = state.artifacts.find(item => item.id === source.id);
      const delivery = source.type === 'delivery' ? deliveryFor(project, source.id) : undefined;
      const url = delivery ? remoteLink(delivery.prUrl) : artifact ? artifactContentHref(artifact) : undefined;
      const review = state.reviews.find(item => item.id === source.reviewId);
      return <div key={sourceIndex}><p>{url ? <a href={url} target="_blank" rel="noreferrer">{source.type === 'delivery' ? `Delivery PR #${delivery?.prNumber}` : source.type === 'release' ? 'Release package' : 'Reviewed artifact'} ↗</a> : <span>{readable(source.type)} · {source.id}</span>} · <code>{source.identity}</code></p><p className="muted">Independent review {shortId(source.reviewId)}{review && <> · <Name id={review.employeeId} state={state}/> · {readable(review.verdict)}</>}</p></div>;
    })}</> : <p className="muted">No completion evidence recorded for this criterion.</p>}</article>;
  })}</div></>;
}
function Projects({ state, selected }: { state: CompanySnapshot; selected?: string }) {
  if (!selected) return <Section title="Project portfolio" note="Finite outcomes, current responsibilities, and actual delivery."><ProjectCards state={state} projects={[...state.projects].sort((a, b) => b.priority - a.priority)}/></Section>;
  const project = state.projects.find((item) => item.id === selected);
  if (!project) return <Empty>Project not found. <a href="#projects">View all projects</a></Empty>;
  const assignments = state.assignments.filter((item) => item.projectId === project.id);
  return <><a className="back-link" href="#projects">← All projects</a><Section title={project.name} action={<Badge value={project.status}/>}><p className="lead-text">{project.outcome}</p><Metadata><Field title="Product">{state.products.find((item) => item.id === project.productId)?.name || 'Company'}</Field><Field title="Supervisor"><Name id={project.supervisorId} state={state}/></Field><Field title="Priority rationale">{project.rationale}</Field><Field title="Workspace"><code>{project.workspace || 'Not provisioned'}</code></Field></Metadata><h3>Acceptance conditions</h3><ProjectAcceptance state={state} project={project}/></Section>
    <ProjectDelivery state={state} project={project}/>
    <Section title="Assignments & dependencies"><AssignmentTable state={state} assignments={assignments}/>{assignments.map((assignment) => <AssignmentDetails key={assignment.id} state={state} assignment={assignment}/>)}</Section>
    <Section title="Artifacts & independent reviews"><Artifacts state={state} artifacts={state.artifacts.filter((item) => item.projectId === project.id)}/></Section><Section title="Project discussion"><Messages state={state} messages={state.messages.filter((item) => item.projectId === project.id)}/><a href={`#conversations/${project.id}`}>Open conversations →</a></Section>
  </>;
}
function Decisions({ state, decisions }: { state: CompanySnapshot; decisions: Decision[] }) {
  return decisions.length ? <div className="records">{[...decisions].reverse().map((decision) => <article className="record" key={decision.id}><div className="card-heading"><h3>{decision.subject}</h3><Badge value={decision.status}/></div><p>{decision.rationale}</p>{decision.appointmentEffect?.summary && <p><strong>Appointment effect:</strong> {decision.appointmentEffect.summary}</p>}<p className="muted"><Name id={decision.authorId} state={state}/> · {date(decision.createdAt)}</p>{state.votes.filter((vote) => vote.decisionId === decision.id).map((vote) => <blockquote className="vote" key={vote.id}><p><strong>{vote.approve ? 'Approve' : 'Dissent'}</strong> · <Name id={vote.employeeId} state={state}/></p><p>{vote.rationale}</p></blockquote>)}<Details value={decision.payload}/></article>)}</div> : <Empty>No decisions recorded yet.</Empty>;
}
function Organization({ state }: { state: CompanySnapshot }) {
  return <><div className="mandate"><p>Three Elders oversee executive appointments and performance. Leadership manages daily work. The Owner retains reserved authority.</p></div><Hierarchy state={state}/><Section title="People & positions" note="An employee keeps their identity through model and position changes."><div className="table-scroll"><table><thead><tr><th>Employee</th><th>Position</th><th>Home manager</th><th>Department</th><th>Status</th></tr></thead><tbody>{state.employees.map((employee) => <tr key={employee.id}><td><a href={`#employees/${employee.id}`}>{employee.name}</a><small>{employee.badge}</small></td><td>{state.positions.find((item) => item.id === employee.positionId)?.title || 'Unassigned'}</td><td><Name id={employee.homeManagerId} state={state}/></td><td>{state.departments.find((item) => item.id === employee.departmentId)?.name || 'Company'}</td><td><Badge value={employeeActivity(state,employee)}/></td></tr>)}</tbody></table></div></Section>
    <Section title="Vacancies">{state.positions.filter((position) => !state.employees.some((employee) => employee.status === 'active' && employee.positionId === position.id)).length ? state.positions.filter((position) => !state.employees.some((employee) => employee.status === 'active' && employee.positionId === position.id)).map((position) => <article className="record" key={position.id}><h3>{position.title}</h3><p>{position.responsibilities}</p><Badge value={position.status}/></article>) : <Empty>No unoccupied positions.</Empty>}</Section>
    <Section title="Leadership & Elder decisions"><Decisions state={state} decisions={state.decisions}/></Section>
    <Section title="Appointment history"><div className="table-scroll"><table><thead><tr><th>Employee</th><th>Position</th><th>Started</th><th>Ended</th><th>Basis</th></tr></thead><tbody>{state.appointments.map((appointment) => <tr key={appointment.id}><td><Name id={appointment.employeeId} state={state}/></td><td>{state.positions.find((item) => item.id === appointment.positionId)?.title}{appointment.acting && ' (acting)'}</td><td>{date(appointment.startedAt)}</td><td>{appointment.endedAt ? date(appointment.endedAt) : 'Current'}</td><td>{state.decisions.find((item) => item.id === appointment.decisionId)?.subject || 'Founding appointment'}</td></tr>)}</tbody></table></div></Section></>;
}
function EmployeeView({ state, id }: { state: CompanySnapshot; id?: string }) {
  const employee = state.employees.find((item) => item.id === id);
  if (!employee) return <Empty>Employee not found. <a href="#organization">View organization</a></Empty>;
  return <><a href="#organization" className="back-link">← Organization</a><Section title={employeeDisplayName(employee, state.employees)} action={<Badge value={employee.status}/>}><Metadata><Field title="Employee identity"><code>{employee.badge} · {employee.id}</code></Field><Field title="Position">{state.positions.find((item) => item.id === employee.positionId)?.title}</Field><Field title="Home manager"><Name id={employee.homeManagerId} state={state}/></Field><Field title="Model">{state.models.find((item) => item.id === employee.modelId)?.name || employee.modelId}</Field><Field title="Department">{state.departments.find((item) => item.id === employee.departmentId)?.name || 'Company'}</Field><Field title="Role version">{employee.roleVersion}</Field></Metadata><details className="assignment-detail"><summary>Role instructions</summary><pre>{employee.role}</pre></details></Section>
    <Section title="Responsibilities & work"><AssignmentTable state={state} assignments={state.assignments.filter((item) => item.employeeId === employee.id)}/>{state.assignments.filter((item) => item.employeeId === employee.id && !item.projectId).map((assignment) => <AssignmentDetails key={assignment.id} state={state} assignment={assignment}/>)}</Section>
    <div className="two-column"><Section title="Experience & performance"><Records items={state.experiences.filter((item) => item.employeeId === employee.id)} empty="Experience is recorded from actual work and feedback." render={(item) => <><h3>{String(item.title || item.summary || 'Experience')}</h3><p>{String(item.learned || item.lesson || item.outcome || item.content || '')}</p><Details value={item}/></>}/></Section><Section title="Role history"><Records items={state.roleVersions.filter((item) => item.employeeId === employee.id)} empty="No developed role revisions yet." render={(item) => <><h3>Version {String(item.version || '')}</h3><p>{String(item.reason || item.rationale || '')}</p><Details value={item}/></>}/></Section></div>
    <Section title="Attributed conversation"><Messages state={state} messages={state.messages.filter((item) => item.senderId === employee.id || item.recipientId === employee.id)}/><a href={`#conversations/employee:${employee.id}`}>Message {employeeDisplayName(employee, state.employees)} →</a></Section>
    <Section title="Knowledge"><KnowledgeLinks items={state.knowledge.filter((item) => item.scopeId === employee.id)}/></Section>
  </>;
}
function Messages({ state, messages }: { state: CompanySnapshot; messages: CompanySnapshot['messages'] }) { return messages.length ? <div className="messages">{messages.map((message) => <article key={message.id} className={`message ${message.senderId === 'owner' ? 'from-owner' : ''}`}><div className="message-meta"><strong><Name id={message.senderId} state={state}/></strong><time>{date(message.createdAt)}</time></div><p className="preserve-lines">{message.content}</p>{message.runId && <small className="muted">Employee run {shortId(message.runId)}</small>}</article>)}</div> : <Empty>No messages in this conversation. Owner messages are optional; the company can choose its own work.</Empty>; }
type Mutate = (path: string, body: unknown, success: string) => Promise<unknown>;
function Conversations({ state, mutate, pending }: { state: CompanySnapshot; mutate: Mutate; pending: boolean }) {
  const [target, setTarget] = useState(() => { const id = parseRoute().id; return id ? id.startsWith('employee:') ? id : `project:${id}` : 'ceo'; });
  const [draft, setDraft] = useState(''); const [sending, setSending] = useState(false);
  const ceo = state.employees.find((employee) => employee.status === 'active' && state.positions.find((position) => position.id === employee.positionId)?.level === 'ceo');
  const recipient = target === 'ceo' ? ceo?.id : target.startsWith('employee:') ? target.slice(9) : undefined;
  const project = target.startsWith('project:') ? target.slice(8) : undefined;
  const messages = state.messages.filter((message) => project ? message.projectId === project : !message.channelId && !message.projectId && (message.senderId === recipient || message.recipientId === recipient));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!draft.trim()) return; setSending(true); try { await mutate('chat', { content: draft.trim(), ...(project ? { projectId: project } : recipient ? { employeeId: recipient } : {}) }, 'Message saved.'); setDraft(''); } catch { /* The page notice retains the error. */ } finally { setSending(false); } };
  return <Section title="Company conversations" note="Durable messages, attributed to the employee who actually responds."><label className="field-label" htmlFor="conversation-target">Conversation</label><select id="conversation-target" value={target} onChange={(event) => setTarget(event.target.value)}><option value="ceo">CEO · {ceo ? employeeDisplayName(ceo, state.employees) : 'Awaiting appointment'}</option><optgroup label="Employees">{state.employees.filter((employee) => employee.status === 'active' && employee.id !== ceo?.id).map((employee) => <option key={employee.id} value={`employee:${employee.id}`}>{employeeDisplayName(employee, state.employees)}</option>)}</optgroup><optgroup label="Projects">{state.projects.map((project) => <option key={project.id} value={`project:${project.id}`}>{project.name}</option>)}</optgroup></select><Messages state={state} messages={messages}/><form className="composer" onSubmit={(event) => { void submit(event); }}><label htmlFor="message-draft">Message</label><textarea id="message-draft" placeholder="Share context, ask a question, or change direction…" value={draft} maxLength={20000} onChange={(event) => setDraft(event.target.value)} rows={4}/><div className="composer-footer"><small>Work continues without an Owner message.</small><button disabled={sending || pending || !draft.trim() || (!recipient && !project)} type="submit">{sending ? 'Saving…' : 'Send message'}</button></div></form></Section>;
}
function KnowledgeLinks({ items }: { items: Knowledge[] }) { return items.length ? <div className="knowledge-list">{items.map((item) => <a key={item.id} href={`#knowledge/${item.id}`}><div><strong>{item.title}</strong><small>{item.path}</small></div><span>{item.scope} · v{item.version}</span></a>)}</div> : <Empty>No knowledge entries in this scope.</Empty>; }
function KnowledgeView({ state, selected }: { state: CompanySnapshot; selected?: string }) {
  const [query, setQuery] = useState(''); const [results, setResults] = useState<Knowledge[]>(state.knowledge); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [document, setDocument] = useState<(Knowledge & { content: string })>();
  useEffect(() => { if (!query) setResults(state.knowledge); }, [query, state.knowledge]);
  const selectedHash = state.knowledge.find((item) => item.id === selected)?.hash;
  useEffect(() => { const abort = new AbortController(); setDocument(undefined); setError(''); if (!selected) return; setLoading(true); void request<Knowledge & { content: string }>(`knowledge/${encodeURIComponent(selected)}`, undefined, abort.signal).then(setDocument).catch((failure: unknown) => { if (!abort.signal.aborted) setError(failure instanceof Error ? failure.message : 'Cannot open knowledge'); }).finally(() => { if (!abort.signal.aborted) setLoading(false); }); return () => abort.abort(); }, [selected, selectedHash]);
  const search = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { setResults(await request<Knowledge[]>(`knowledge?q=${encodeURIComponent(query)}`)); } catch (failure) { setError(failure instanceof Error ? failure.message : 'Search failed'); } finally { setLoading(false); } };
  return <>{selected ? <><a href="#knowledge" className="back-link">← Knowledge vault</a>{loading && <Empty>Opening Markdown…</Empty>}{document && <Section title={document.title} note={`${document.scope} · Version ${document.version} · ${document.humanEdited ? 'Human edited' : 'Company authored'}`} action={<a href={`/api/v1/knowledge/${encodeURIComponent(document.id)}?format=markdown`} target="_blank" rel="noreferrer">Open Markdown ↗</a>}><p className="muted"><code>{document.path}</code></p><pre className="markdown-content">{document.content}</pre><Details value={document.provenance} label="Sources and provenance"/></Section>}</> : <Section title="Knowledge vault" note="Source-linked company knowledge. Operational authority remains in company state."><form className="search-form" onSubmit={(event) => { void search(event); }}><label className="sr-only" htmlFor="knowledge-query">Search knowledge</label><input id="knowledge-query" type="search" placeholder="Search titles, knowledge, and source material" value={query} onChange={(event) => setQuery(event.target.value)}/><button type="submit" disabled={loading}>{loading ? 'Searching…' : 'Search'}</button></form><KnowledgeLinks items={results}/></Section>}{error && <div className="banner error" role="alert">{error}</div>}</>;
}
function AttentionResolution({ id, mutate, pending }: { id: string; mutate: Mutate; pending: boolean }) {
  const [resolution, setResolution] = useState('');
  return <details className="assignment-detail"><summary>Record a completed prerequisite</summary><form className="composer" onSubmit={(event) => { event.preventDefault(); void mutate('command', { type: 'attention.resolve', attentionId: id, resolution }, 'Prerequisite update recorded. Provider and execution checks still apply.').catch(() => {}); }}><label htmlFor={`resolution-${id}`}>What did you complete?</label><textarea id={`resolution-${id}`} rows={2} value={resolution} onChange={(event) => setResolution(event.target.value)} required/><div className="composer-footer"><small>Record the specific access, consent, or device step you completed.</small><button disabled={pending || !resolution.trim()} type="submit">Record resolution</button></div></form></details>;
}
function AttentionView({ state, mutate, pending }: { state: CompanySnapshot; mutate: Mutate; pending: boolean }) {
  const open = state.attention.filter((item) => item.status === 'open');
  return <><Section title="Needs your attention" note="Only exact prerequisites and reserved decisions reach the Owner.">{open.length ? <div className="records">{open.map((item) => { const action = state.actions.find((action) => action.id === item.actionId); return <article className="record" key={item.id}><div className="card-heading"><h3>{item.title}</h3><Badge value={item.kind}/></div><p>{item.detail}</p>{item.requiredAction && <div className="required-action"><strong>Required action</strong><p>{item.requiredAction}</p></div>}{action && <><Metadata><Field title="Destination">{action.target}</Field><Field title="Proposed charge">{action.cost === null ? 'Unknown — cost must be established first' : `$${action.cost.toFixed(2)}`}</Field><Field title="Cost basis">{action.costEvidence}</Field></Metadata><Details value={action.content} label="Exact proposed action"/>{action.status === 'blocked' && action.cost !== null && action.cost > 0 && <button disabled={pending} onClick={() => { void mutate('command', { type: 'action.approveCost', actionId: action.id, amount: action.cost, description: `${action.kind} for ${action.target}: ${action.costEvidence}` }, 'Approved this action and amount only.').catch(() => {}); }}>Approve ${action.cost.toFixed(2)} for this action</button>}</>}{item.ownerId&&<p>Accountable employee: <Name state={state} id={item.ownerId}/></p>}{item.recommendation&&<p><strong>Recommendation:</strong> {item.recommendation}</p>}{item.nextCheckAt&&<p className="muted">Next recheck: {date(item.nextCheckAt)}</p>}{item.notification&&<p className="muted">Notification: {readable(item.notification.status)}{item.notification.detail&&` · ${item.notification.detail}`}</p>}{item.kind==='owner_decision'&&!item.acknowledgedAt&&<button className="quiet" disabled={pending} onClick={()=>{void mutate('command',{type:'attention.acknowledge',attentionId:item.id},'Request seen. Its prerequisite remains open.').catch(()=>{});}}>Mark as seen</button>}{!action && <AttentionResolution id={item.id} mutate={mutate} pending={pending}/>}</article>; })}</div> : <Empty>No Owner action required. Leadership handles routine strategy, staffing, reviews, merges, and zero-cost delivery.</Empty>}</Section><Section title="Resolved requests"><Records items={state.attention.filter((item) => item.status !== 'open')} empty="No resolved requests yet." render={(item) => <><h3>{String(item.title)}</h3><p>{String(item.detail)}</p><Badge value={String(item.status)}/></>}/></Section></>;
}
function SchedulingSettings({ state, mutate, pending }: { state: CompanySnapshot; mutate: Mutate; pending: boolean }) {
  const [minutes, setMinutes] = useState(state.policy.reassessMinutes); const [retries, setRetries] = useState(state.policy.maxRetries); const [corrections, setCorrections] = useState(state.policy.maxCorrections);
  return <details className="assignment-detail"><summary>Adjust scheduling limits</summary><form className="schedule-form" onSubmit={(event) => { event.preventDefault(); void mutate('command', { type: 'policy.update', reassessMinutes: minutes, maxRetries: retries, maxCorrections: corrections }, 'Scheduling limits saved.').catch(() => {}); }}><label>Idle reassessment (minutes)<input type="number" min={1} max={1440} value={minutes} onChange={(event) => setMinutes(Number(event.target.value))} required/></label><label>Transient retries<select value={retries} onChange={(event) => setRetries(Number(event.target.value))}><option value={0}>0</option><option value={1}>1</option></select></label><label>Correction revisions<select value={corrections} onChange={(event) => setCorrections(Number(event.target.value))}><option value={1}>1</option><option value={2}>2</option></select></label><button type="submit" disabled={pending}>Save limits</button></form></details>;
}
function Settings({ state, mutate, pending, control }: { state: CompanySnapshot; mutate: Mutate; pending: boolean; control: (action: string) => Promise<void> }) {
  const [backup, setBackup] = useState<unknown>(); const [restore, setRestore] = useState(''); const [restoring, setRestoring] = useState(false); const [doctor, setDoctor] = useState<unknown>();
  return <><Section title="Owner policy"><Metadata><Field title="Unapproved spending">${state.policy.spendingLimit.toFixed(2)}</Field><Field title="Inference">{state.policy.localOnly ? 'Local only · no cloud fallback' : 'Policy error: local-only requirement is disabled'}</Field><Field title="Policy revision">{state.policy.revision}</Field><Field title="Authorized products">{state.products.map((product) => product.name).join(', ')}</Field></Metadata><p className="muted">Routine product implementation, independent review, merges, zero-cost releases, and communications are delegated. New cost requires approval for the exact action and amount.</p></Section>
    <Section title="Scheduling & resources"><Metadata><Field title="Inference slots">{state.policy.maxInference}</Field><Field title="Exclusive native jobs">{state.policy.nativeJobs}</Field><Field title="Strategic reassessment">Every {state.policy.reassessMinutes} minutes when idle</Field><Field title="Technical retries">{state.policy.maxRetries}</Field><Field title="Correction revisions">{state.policy.maxCorrections}</Field></Metadata><SchedulingSettings key={state.policy.revision} state={state} mutate={mutate} pending={pending}/><Details value={state.resources} label="Actual host and process resources"/></Section>
    <Section title="Local models"><div className="records">{state.models.map((model) => <article className="record" key={model.id}><div className="card-heading"><h3>{model.name}</h3><Badge value={model.available ? 'available' : 'unavailable'}/></div><p>{model.capabilities.join(' · ') || 'Capabilities not yet verified'}</p><small className="mono">{model.artifactIdentity || 'Artifact identity not yet resolved'}</small><Details value={model}/></article>)}{!state.models.length && <Empty>Local model discovery has not completed.</Empty>}</div></Section>
    <Section title="Integrations"><div className="records">{state.integrations.map((integration) => <article className="record" key={integration.id}><div className="card-heading"><h3>{integration.name}</h3><Badge value={integration.status}/></div><p>{integration.detail}</p></article>)}{!state.integrations.length && <Empty>No integration checks recorded yet.</Empty>}</div></Section>
    <Section title="Service controls" note="Pause and stop persist through restart. Closing an interface leaves the service running."><div className="button-row"><button disabled={pending || state.company.state === 'running'} onClick={() => { void control(state.company.state === 'paused' ? 'resume' : 'start'); }}>Start / resume</button><button disabled={pending || state.company.state !== 'running'} onClick={() => { void control('pause'); }}>Pause company</button><button className="quiet danger" disabled={pending || state.company.state === 'stopped'} onClick={() => { void control('stop'); }}>Stop company</button></div><p className="muted">LaunchAgent management: <code>opencorp service install</code> · <code>opencorp service status</code> · <code>opencorp service uninstall</code></p><button className="quiet" disabled={pending} onClick={() => { void request('doctor').then(setDoctor).catch((failure: unknown) => setDoctor({ error: failure instanceof Error ? failure.message : 'Doctor failed' })); }}>Run doctor</button>{doctor !== undefined && <pre>{contentText(doctor)}</pre>}</Section>
    <Section title="Backup & restore" note="Backups include the operational database and Markdown vault. Restore protects against repeated external effects."><button disabled={pending} onClick={() => { void mutate('backup', {}, 'Backup created.').then(setBackup).catch(() => {}); }}>Create backup</button>{backup !== undefined && <pre>{contentText(backup)}</pre>}<form className="restore-form" onSubmit={(event) => { event.preventDefault(); setRestoring(true); }}><label htmlFor="restore-path">Backup directory</label><input id="restore-path" value={restore} onChange={(event) => setRestore(event.target.value)} placeholder="Absolute path to an OpenCorp backup" required/><button className="quiet" disabled={pending || !restore.startsWith('/') || !['paused', 'stopped'].includes(state.company.state)} type="submit">Review restore</button></form>{!['paused', 'stopped'].includes(state.company.state) && <p className="muted">Pause the company before restoring a backup.</p>}{restoring && <div className="banner"><strong>Restore this backup?</strong><p>Current company state will be replaced from <code>{restore}</code>. External actions must be reconciled before they can run again.</p><div className="button-row"><button disabled={pending} onClick={() => { void mutate('restore', { path: restore }, 'Backup restored. Review company state before resuming.').then(() => setRestoring(false)).catch(() => {}); }}>Restore backup</button><button className="quiet" onClick={() => setRestoring(false)}>Cancel</button></div></div>}</Section>
  </>;
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
